using System;
using System.Collections.Generic;

#nullable disable

namespace Layer.Core.Models
{
    public partial class LCapiuser
    {
        public int Logicalref { get; set; }
        public short? Nr { get; set; }
        public string Name { get; set; }
        public string Key { get; set; }
        public short? Groups1 { get; set; }
        public short? Groups2 { get; set; }
        public short? Groups3 { get; set; }
        public short? Groups4 { get; set; }
        public short? Groups5 { get; set; }
        public short? Groups6 { get; set; }
        public short? Groups7 { get; set; }
        public short? Groups8 { get; set; }
        public short? Groups9 { get; set; }
        public short? Groups10 { get; set; }
        public short? Groups11 { get; set; }
        public short? Groups12 { get; set; }
        public short? Groups13 { get; set; }
        public short? Groups14 { get; set; }
        public short? Groups15 { get; set; }
        public short? Groups16 { get; set; }
        public short? Groups17 { get; set; }
        public short? Groups18 { get; set; }
        public short? Groups19 { get; set; }
        public short? Groups20 { get; set; }
        public short? Groups21 { get; set; }
        public short? Groups22 { get; set; }
        public short? Groups23 { get; set; }
        public short? Groups24 { get; set; }
        public short? Groups25 { get; set; }
        public short? Groups26 { get; set; }
        public short? Groups27 { get; set; }
        public short? Groups28 { get; set; }
        public short? Groups29 { get; set; }
        public short? Groups30 { get; set; }
        public short? Groups31 { get; set; }
        public short? Groups32 { get; set; }
        public short? Groups33 { get; set; }
        public short? Groups34 { get; set; }
        public short? Groups35 { get; set; }
        public short? Groups36 { get; set; }
        public short? Groups37 { get; set; }
        public short? Groups38 { get; set; }
        public short? Groups39 { get; set; }
        public short? Groups40 { get; set; }
        public short? Groups41 { get; set; }
        public short? Groups42 { get; set; }
        public short? Groups43 { get; set; }
        public short? Groups44 { get; set; }
        public short? Groups45 { get; set; }
        public short? Groups46 { get; set; }
        public short? Groups47 { get; set; }
        public short? Groups48 { get; set; }
        public short? Groups49 { get; set; }
        public short? Groups50 { get; set; }
        public short? Groups51 { get; set; }
        public short? Groups52 { get; set; }
        public short? Groups53 { get; set; }
        public short? Groups54 { get; set; }
        public short? Groups55 { get; set; }
        public short? Groups56 { get; set; }
        public short? Groups57 { get; set; }
        public short? Groups58 { get; set; }
        public short? Groups59 { get; set; }
        public short? Groups60 { get; set; }
        public short? Groups61 { get; set; }
        public short? Groups62 { get; set; }
        public short? Groups63 { get; set; }
        public short? Groups64 { get; set; }
        public short? Groups65 { get; set; }
        public short? Groups66 { get; set; }
        public short? Groups67 { get; set; }
        public short? Groups68 { get; set; }
        public short? Groups69 { get; set; }
        public short? Groups70 { get; set; }
        public short? Groups71 { get; set; }
        public short? Groups72 { get; set; }
        public short? Groups73 { get; set; }
        public short? Groups74 { get; set; }
        public short? Groups75 { get; set; }
        public short? Groups76 { get; set; }
        public short? Groups77 { get; set; }
        public short? Groups78 { get; set; }
        public short? Groups79 { get; set; }
        public short? Groups80 { get; set; }
        public short? Groups81 { get; set; }
        public short? Groups82 { get; set; }
        public short? Groups83 { get; set; }
        public short? Groups84 { get; set; }
        public short? Groups85 { get; set; }
        public short? Groups86 { get; set; }
        public short? Groups87 { get; set; }
        public short? Groups88 { get; set; }
        public short? Groups89 { get; set; }
        public short? Groups90 { get; set; }
        public short? Groups91 { get; set; }
        public short? Groups92 { get; set; }
        public short? Groups93 { get; set; }
        public short? Groups94 { get; set; }
        public short? Groups95 { get; set; }
        public short? Groups96 { get; set; }
        public short? Groups97 { get; set; }
        public short? Groups98 { get; set; }
        public short? Groups99 { get; set; }
        public short? Groups100 { get; set; }
        public short? Firmnr { get; set; }
        public short? Lang { get; set; }
        public short? Options { get; set; }
        public short? Blocked { get; set; }
        public short? Logflag { get; set; }
        public string Intfres { get; set; }
        public string Emaila { get; set; }
        public short? Defrole { get; set; }
        public short? Roles1 { get; set; }
        public short? Roles2 { get; set; }
        public short? Roles3 { get; set; }
        public short? Roles4 { get; set; }
        public short? Roles5 { get; set; }
        public int? Userext { get; set; }
        public short? Uniflog { get; set; }
        public short? Dmconn { get; set; }
        public short? Webconn { get; set; }
        public short? Extroles1 { get; set; }
        public short? Extroles2 { get; set; }
        public short? Extroles3 { get; set; }
        public short? Extroles4 { get; set; }
        public short? Extroles5 { get; set; }
        public short? Seller { get; set; }
        public string Specode { get; set; }
        public string Cyphcode { get; set; }
        public short? Divnr { get; set; }
        public short? Deptnr { get; set; }
        public short? Whnr { get; set; }
        public DateTime? Keycdate { get; set; }
        public short? Disabled { get; set; }
        public short? Prclimitgrp { get; set; }
        public short? Budgetadmin { get; set; }
        public string Prevkey1 { get; set; }
        public string Prevkey2 { get; set; }
        public short? Focusadmin { get; set; }
        public short? Blockedtheme { get; set; }
        public short? Factnr { get; set; }
        public short? Activedirectoryuser { get; set; }
        public short? Adusercannotmodify { get; set; }
        public short? Singlesignon { get; set; }
        public short? Workspace { get; set; }
        public short? Localcaldr { get; set; }
        public short? Forcerelogin { get; set; }
        public short? Failedlogins { get; set; }
        public string Phoneno { get; set; }
        public short? Loginblckcnt { get; set; }
        public string Username { get; set; }
        public string Usersurname { get; set; }
        public string Mobilsecuritycode { get; set; }
        public string Forcereloginmsg { get; set; }
        public short? Dontshowlogobipage { get; set; }
        public short? Onlyobject { get; set; }
        public short? Objectfullright { get; set; }
        public string Faxusername { get; set; }
        public string Faxuserkey { get; set; }
        public string Faxuseremail { get; set; }
        public string KeyMd5 { get; set; }
        public short? Accesstype { get; set; }
        public short? Usertype { get; set; }
        public short? Kvkkuser { get; set; }
        public string Usrprojectcode { get; set; }
        public short? Selleradmin { get; set; }
        public string Payrollusername { get; set; }
        public string Payrolluserkey { get; set; }
        public string Idmloginname { get; set; }
        public short? Idmtransferred { get; set; }
        public short? Useidmuser { get; set; }
    }
}
