using System;
using System.Collections.Generic;

#nullable disable

namespace Layer.Core.Models
{
    public partial class Lg00101Orfiche
    {
        public int Logicalref { get; set; }
        public short? Trcode { get; set; }
        public string Ficheno { get; set; }
        public DateTime? Date { get; set; }
        public int? Time { get; set; }
        public string Docode { get; set; }
        public string Specode { get; set; }
        public string Cyphcode { get; set; }
        public int? Clientref { get; set; }
        public int? Recvref { get; set; }
        public int? Accountref { get; set; }
        public int? Centerref { get; set; }
        public short? Sourceindex { get; set; }
        public short? Sourcecostgrp { get; set; }
        public short? Updcurr { get; set; }
        public double? Adddiscounts { get; set; }
        public double? Totaldiscounts { get; set; }
        public double? Totaldiscounted { get; set; }
        public double? Addexpenses { get; set; }
        public double? Totalexpenses { get; set; }
        public double? Totalpromotions { get; set; }
        public double? Totalvat { get; set; }
        public double? Grosstotal { get; set; }
        public double? Nettotal { get; set; }
        public double? Reportrate { get; set; }
        public double? Reportnet { get; set; }
        public string Genexp1 { get; set; }
        public string Genexp2 { get; set; }
        public string Genexp3 { get; set; }
        public string Genexp4 { get; set; }
        public string Genexp5 { get; set; }
        public string Genexp6 { get; set; }
        public int? Extenref { get; set; }
        public int? Paydefref { get; set; }
        public short? Printcnt { get; set; }
        public short? Branch { get; set; }
        public short? Department { get; set; }
        public short? Status { get; set; }
        public short? CapiblockCreatedby { get; set; }
        public DateTime? CapiblockCreadeddate { get; set; }
        public short? CapiblockCreatedhour { get; set; }
        public short? CapiblockCreatedmin { get; set; }
        public short? CapiblockCreatedsec { get; set; }
        public short? CapiblockModifiedby { get; set; }
        public DateTime? CapiblockModifieddate { get; set; }
        public short? CapiblockModifiedhour { get; set; }
        public short? CapiblockModifiedmin { get; set; }
        public short? CapiblockModifiedsec { get; set; }
        public int? Salesmanref { get; set; }
        public string Shptypcod { get; set; }
        public string Shpagncod { get; set; }
        public short? Genexctyp { get; set; }
        public short? Lineexctyp { get; set; }
        public string Tradinggrp { get; set; }
        public short? Textinc { get; set; }
        public short? Siteid { get; set; }
        public short? Recstatus { get; set; }
        public int? Orglogicref { get; set; }
        public short? Factorynr { get; set; }
        public int? Wfstatus { get; set; }
        public int? Shipinforef { get; set; }
        public string Custordno { get; set; }
        public short? Sendcnt { get; set; }
        public short? Dlvclient { get; set; }
        public string Doctrackingnr { get; set; }
        public short? Cancelled { get; set; }
        public string Orglogoid { get; set; }
        public int? Offerref { get; set; }
        public int? Offaltref { get; set; }
        public short? Typ { get; set; }
        public short? Altnr { get; set; }
        public double? Advancepaym { get; set; }
        public short? Trcurr { get; set; }
        public double? Trrate { get; set; }
        public double? Trnet { get; set; }
        public short? Paymenttype { get; set; }
        public short? Onlyonepayline { get; set; }
        public short? Opstat { get; set; }
        public short? Withpaytrans { get; set; }
        public int? Projectref { get; set; }
        public int? Wflowcrdref { get; set; }
        public short? Updtrcurr { get; set; }
        public short? Affectcollatrl { get; set; }
        public DateTime? Pofferbegdt { get; set; }
        public DateTime? Pofferenddt { get; set; }
        public string Revisnr { get; set; }
        public short? Lastrevision { get; set; }
        public short? Checkamount { get; set; }
        public int? Slsopprref { get; set; }
        public int? Slsactref { get; set; }
        public int? Slscustref { get; set; }
        public short? Affectrisk { get; set; }
        public double? Totaladdtax { get; set; }
        public double? Totalexaddtax { get; set; }
        public short? Approve { get; set; }
        public DateTime? Approvedate { get; set; }
        public short? Checkprice { get; set; }
        public short? Transferwithpay { get; set; }
        public int? Fcstatusref { get; set; }
        public short? Checktotal { get; set; }
        public string Guid { get; set; }
        public short? Cantcrededuct { get; set; }
        public short? Deductionpart1 { get; set; }
        public short? Deductionpart2 { get; set; }
        public string Globalid { get; set; }
        public short? Defaultfiche { get; set; }
        public int? Leasingref { get; set; }
        public string Campaigncode { get; set; }
        public double? Addexpensesvat { get; set; }
        public double? Totalexpensesvat { get; set; }
        public short? Devir { get; set; }
        public DateTime? Printdate { get; set; }
        public string Deliverycode { get; set; }
        public short? Einvoicetyp { get; set; }
        public short? Einvoice { get; set; }
        public int? Publicbnaccref { get; set; }
        public short? Accepteinvpublic { get; set; }
        public short? Insteadofdesp { get; set; }
        public string Vatexceptcode { get; set; }
        public string Vatexceptreason { get; set; }
        public string Ataxexceptcode { get; set; }
        public string Ataxexceptreason { get; set; }
        public short? Taxfreechx { get; set; }
        public DateTime? Orgdate { get; set; }
        public short? Actrenting { get; set; }
        public double? Adddiscountsvat { get; set; }
        public int? Notifycrdref { get; set; }
    }
}
