using System;
using System.Collections.Generic;

#nullable disable

namespace Layer.Core.Models
{
    public partial class Lg001Purchofferln
    {
        public int Logicalref { get; set; }
        public int? Stockref { get; set; }
        public int? Ordficheref { get; set; }
        public int? Clientref { get; set; }
        public short? Linetype { get; set; }
        public int? Prevlineref { get; set; }
        public short? Prevlineno { get; set; }
        public short? Detline { get; set; }
        public short? Lineno { get; set; }
        public short? Trcode { get; set; }
        public DateTime? Date { get; set; }
        public int? Time { get; set; }
        public short? Globtrans { get; set; }
        public short? Calctype { get; set; }
        public int? Centerref { get; set; }
        public int? Accountref { get; set; }
        public int? Vataccref { get; set; }
        public int? Vatcenterref { get; set; }
        public int? Praccref { get; set; }
        public int? Prcenterref { get; set; }
        public int? Prvataccref { get; set; }
        public int? Prvatcenref { get; set; }
        public int? Promref { get; set; }
        public string Specode { get; set; }
        public string Delvrycode { get; set; }
        public double? Amount { get; set; }
        public double? Price { get; set; }
        public double? Total { get; set; }
        public double? Shippedamount { get; set; }
        public double? Discper { get; set; }
        public double? Distcost { get; set; }
        public double? Distdisc { get; set; }
        public double? Distexp { get; set; }
        public double? Distprom { get; set; }
        public double? Vat { get; set; }
        public double? Vatamnt { get; set; }
        public double? Vatmatrah { get; set; }
        public string Lineexp { get; set; }
        public int? Uomref { get; set; }
        public int? Usref { get; set; }
        public double? Uinfo1 { get; set; }
        public double? Uinfo2 { get; set; }
        public double? Uinfo3 { get; set; }
        public double? Uinfo4 { get; set; }
        public double? Uinfo5 { get; set; }
        public double? Uinfo6 { get; set; }
        public double? Uinfo7 { get; set; }
        public double? Uinfo8 { get; set; }
        public short? Vatinc { get; set; }
        public short? Closed { get; set; }
        public short? Doreserve { get; set; }
        public short? Inuse { get; set; }
        public DateTime? Duedate { get; set; }
        public short? Prcurr { get; set; }
        public double? Prprice { get; set; }
        public double? Reportrate { get; set; }
        public int? Billeditem { get; set; }
        public int? Paydefref { get; set; }
        public int? Extenref { get; set; }
        public short? Cpstflag { get; set; }
        public short? Sourceindex { get; set; }
        public short? Sourcecostgrp { get; set; }
        public short? Branch { get; set; }
        public short? Department { get; set; }
        public double? Linenet { get; set; }
        public int? Salesmanref { get; set; }
        public short? Status { get; set; }
        public int? Dref { get; set; }
        public short? Trgflag { get; set; }
        public short? Siteid { get; set; }
        public short? Recstatus { get; set; }
        public int? Orglogicref { get; set; }
        public short? Factorynr { get; set; }
        public int? Wfstatus { get; set; }
        public short? Netdiscflag { get; set; }
        public double? Netdiscperc { get; set; }
        public double? Netdiscamnt { get; set; }
        public int? Conditionref { get; set; }
        public double? Distreserved { get; set; }
        public double? Onvehicle { get; set; }
        public int? Campaignrefs1 { get; set; }
        public int? Campaignrefs2 { get; set; }
        public int? Campaignrefs3 { get; set; }
        public int? Campaignrefs4 { get; set; }
        public int? Campaignrefs5 { get; set; }
        public int? Pointcampref { get; set; }
        public double? Camppoint { get; set; }
        public int? Promclasitemref { get; set; }
        public short? Reasonfornotshp { get; set; }
        public int? Cmpglineref { get; set; }
        public double? Prrate { get; set; }
        public double? Grossuinfo1 { get; set; }
        public double? Grossuinfo2 { get; set; }
        public short? Cancelled { get; set; }
        public double? Dempeggedamnt { get; set; }
        public short? Textinc { get; set; }
        public int? Offerref { get; set; }
        public short? Orderparam { get; set; }
        public int? Itemasgref { get; set; }
        public double? Eximamount { get; set; }
        public int? Offtransref { get; set; }
        public double? Orderedamount { get; set; }
        public string Orglogoid { get; set; }
        public short? Trcurr { get; set; }
        public double? Trrate { get; set; }
        public short? Withpaytrans { get; set; }
        public int? Projectref { get; set; }
        public int? Pointcamprefs1 { get; set; }
        public int? Pointcamprefs2 { get; set; }
        public int? Pointcamprefs3 { get; set; }
        public int? Pointcamprefs4 { get; set; }
        public double? Camppoints1 { get; set; }
        public double? Camppoints2 { get; set; }
        public double? Camppoints3 { get; set; }
        public double? Camppoints4 { get; set; }
        public int? Cmpglinerefs1 { get; set; }
        public int? Cmpglinerefs2 { get; set; }
        public int? Cmpglinerefs3 { get; set; }
        public int? Cmpglinerefs4 { get; set; }
        public int? Prclistref { get; set; }
        public short? Affectcollatrl { get; set; }
        public short? Fctyp { get; set; }
        public short? Purchoffnr { get; set; }
        public int? Demficheref { get; set; }
        public int? Demtransref { get; set; }
        public short? Altpromflag { get; set; }
        public int? Variantref { get; set; }
        public int? Reflvataccref { get; set; }
        public int? Reflvatothaccref { get; set; }
        public short? Priority { get; set; }
        public short? Affectrisk { get; set; }
        public int? Bomref { get; set; }
        public int? Bomrevref { get; set; }
        public int? Routingref { get; set; }
        public int? Operationref { get; set; }
        public int? Wsref { get; set; }
        public double? Addtaxrate { get; set; }
        public double? Addtaxconvfact { get; set; }
        public double? Addtaxamount { get; set; }
        public int? Addtaxaccref { get; set; }
        public int? Addtaxcenterref { get; set; }
        public short? Addtaxamntisupd { get; set; }
        public double? Addtaxdiscamount { get; set; }
        public double? Exaddtaxrate { get; set; }
        public double? Exaddtaxconvf { get; set; }
        public double? Exaddtaxamnt { get; set; }
        public int? Euvatstatus { get; set; }
        public double? Addtaxvatmatrah { get; set; }
        public int? Camppaydefref { get; set; }
        public double? Rprice { get; set; }
        public DateTime? Orgduedate { get; set; }
        public double? Orgamount { get; set; }
        public double? Orgprice { get; set; }
        public string Specode2 { get; set; }
        public DateTime? Reservedate { get; set; }
        public short? Candeduct { get; set; }
        public short? Underdeductlimit { get; set; }
        public string Globalid { get; set; }
        public short? Deductionpart1 { get; set; }
        public short? Deductionpart2 { get; set; }
        public int? Parentlnref { get; set; }
        public string Guid { get; set; }
        public double? Distexpvat { get; set; }
        public double? Shippedamntsugg { get; set; }
        public double? Reserveamount { get; set; }
        public string Deductcode { get; set; }
        public short? Bomtype { get; set; }
        public short? Devir { get; set; }
        public int? Faregref { get; set; }
        public string Vatexceptcode { get; set; }
        public string Vatexceptreason { get; set; }
        public string Ataxexceptcode { get; set; }
        public string Ataxexceptreason { get; set; }
        public string Cpacode { get; set; }
        public string Gtipcode { get; set; }
        public int? Publiccountryref { get; set; }
        public double? Distdiscvat { get; set; }
    }
}
