using System;
using System.Collections.Generic;

#nullable disable

namespace Layer.Core.Models
{
    public partial class Lg001Item
    {
        public int Logicalref { get; set; }
        public short? Active { get; set; }
        public short? Cardtype { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Stgrpcode { get; set; }
        public string Producercode { get; set; }
        public string Specode { get; set; }
        public string Cyphcode { get; set; }
        public short? Classtype { get; set; }
        public short? Purchbrws { get; set; }
        public short? Salesbrws { get; set; }
        public short? Mtrlbrws { get; set; }
        public double? Vat { get; set; }
        public int? Paymentref { get; set; }
        public short? Tracktype { get; set; }
        public short? Loctracking { get; set; }
        public short? Tool { get; set; }
        public short? Autoincsl { get; set; }
        public short? Divlotsize { get; set; }
        public double? Shelflife { get; set; }
        public short? Shelfdate { get; set; }
        public int? Dominantrefs1 { get; set; }
        public int? Dominantrefs2 { get; set; }
        public int? Dominantrefs3 { get; set; }
        public int? Dominantrefs4 { get; set; }
        public int? Dominantrefs5 { get; set; }
        public int? Dominantrefs6 { get; set; }
        public int? Dominantrefs7 { get; set; }
        public int? Dominantrefs8 { get; set; }
        public int? Dominantrefs9 { get; set; }
        public int? Dominantrefs10 { get; set; }
        public int? Dominantrefs11 { get; set; }
        public int? Dominantrefs12 { get; set; }
        public short? Imageinc { get; set; }
        public short? Textinc { get; set; }
        public short? Deprtype { get; set; }
        public double? Deprrate { get; set; }
        public short? Deprdur { get; set; }
        public double? Salvageval { get; set; }
        public short? Revalflag { get; set; }
        public short? Revdeprflag { get; set; }
        public short? Partdep { get; set; }
        public short? Deprtype2 { get; set; }
        public double? Deprrate2 { get; set; }
        public short? Deprdur2 { get; set; }
        public short? Revalflag2 { get; set; }
        public short? Revdeprflag2 { get; set; }
        public short? Partdep2 { get; set; }
        public short? Approved { get; set; }
        public int? Unitsetref { get; set; }
        public int? Qccsetref { get; set; }
        public double? Distamount { get; set; }
        public short? CapiblockCreatedby { get; set; }
        public DateTime? CapiblockCreadeddate { get; set; }
        public short? CapiblockCreatedhour { get; set; }
        public short? CapiblockCreatedmin { get; set; }
        public short? CapiblockCreatedsec { get; set; }
        public short? CapiblockModifiedby { get; set; }
        public DateTime? CapiblockModifieddate { get; set; }
        public short? CapiblockModifiedhour { get; set; }
        public short? CapiblockModifiedmin { get; set; }
        public short? CapiblockModifiedsec { get; set; }
        public short? Siteid { get; set; }
        public short? Recstatus { get; set; }
        public int? Orglogicref { get; set; }
        public string Univid { get; set; }
        public short? Distlotunits { get; set; }
        public short? Comblotunits { get; set; }
        public int? Wfstatus { get; set; }
        public double? Distpoint { get; set; }
        public double? Camppoint { get; set; }
        public short? Canuseintrns { get; set; }
        public string Isonr { get; set; }
        public string Groupnr { get; set; }
        public string Prodcountry { get; set; }
        public int? Addtaxref { get; set; }
        public double? Qprodamnt { get; set; }
        public int? Qproduom { get; set; }
        public short? Qprodsrcindex { get; set; }
        public int? Extaccessflags { get; set; }
        public short? Packet { get; set; }
        public double? Salvageval2 { get; set; }
        public double? Sellvat { get; set; }
        public double? Returnvat { get; set; }
        public string Logoid { get; set; }
        public short? Lidconfirmed { get; set; }
        public string Gtipcode { get; set; }
        public string Expctgno { get; set; }
        public string B2ccode { get; set; }
        public int? Markref { get; set; }
        public short? Image2inc { get; set; }
        public double? Avrwhduration { get; set; }
        public int? Extcardflags { get; set; }
        public double? Minordamount { get; set; }
        public string Freightplace { get; set; }
        public string Freighttypcode1 { get; set; }
        public string Freighttypcode2 { get; set; }
        public string Freighttypcode3 { get; set; }
        public string Freighttypcode4 { get; set; }
        public string Freighttypcode5 { get; set; }
        public string Freighttypcode6 { get; set; }
        public string Freighttypcode7 { get; set; }
        public string Freighttypcode8 { get; set; }
        public string Freighttypcode9 { get; set; }
        public string Freighttypcode10 { get; set; }
        public string Statecode { get; set; }
        public string Statename { get; set; }
        public string Expcategory { get; set; }
        public double? Lostfactor { get; set; }
        public short? Textinceng { get; set; }
        public string Eanbarcode { get; set; }
        public string Deprclasstype { get; set; }
        public int? Wflowcrdref { get; set; }
        public double? Sellprvat { get; set; }
        public double? Returnprvat { get; set; }
        public int? Lowlevelcodes1 { get; set; }
        public int? Lowlevelcodes2 { get; set; }
        public int? Lowlevelcodes3 { get; set; }
        public int? Lowlevelcodes4 { get; set; }
        public int? Lowlevelcodes5 { get; set; }
        public int? Lowlevelcodes6 { get; set; }
        public int? Lowlevelcodes7 { get; set; }
        public int? Lowlevelcodes8 { get; set; }
        public int? Lowlevelcodes9 { get; set; }
        public int? Lowlevelcodes10 { get; set; }
        public string Orglogoid { get; set; }
        public short? Qproddepart { get; set; }
        public short? Canconfigure { get; set; }
        public int? Charsetref { get; set; }
        public short? Candeduct { get; set; }
        public int? Conscoderef { get; set; }
        public string Specode2 { get; set; }
        public string Specode3 { get; set; }
        public string Specode4 { get; set; }
        public string Specode5 { get; set; }
        public short? Expense { get; set; }
        public string Origin { get; set; }
        public string Name2 { get; set; }
        public short? Compkdvuse { get; set; }
        public short? Usedinperiods { get; set; }
        public double? Eximtax1 { get; set; }
        public double? Eximtax2 { get; set; }
        public double? Eximtax3 { get; set; }
        public double? Eximtax4 { get; set; }
        public double? Eximtax5 { get; set; }
        public short? Productlevel { get; set; }
        public short? Appspevatmatrah { get; set; }
        public string Name3 { get; set; }
        public short? Facostkeys { get; set; }
        public short? Kklinesdisable { get; set; }
        public short? Approve { get; set; }
        public DateTime? Approvedate { get; set; }
        public string Globalid { get; set; }
        public short? Saledeductpart1 { get; set; }
        public short? Saledeductpart2 { get; set; }
        public short? Purcdeductpart1 { get; set; }
        public short? Purcdeductpart2 { get; set; }
        public string Categoryid { get; set; }
        public string Categoryname { get; set; }
        public string Keyword1 { get; set; }
        public string Keyword2 { get; set; }
        public string Keyword3 { get; set; }
        public string Keyword4 { get; set; }
        public string Keyword5 { get; set; }
        public string Guid { get; set; }
        public string Demandmeetsortfld1 { get; set; }
        public string Demandmeetsortfld2 { get; set; }
        public string Demandmeetsortfld3 { get; set; }
        public string Demandmeetsortfld4 { get; set; }
        public string Demandmeetsortfld5 { get; set; }
        public string Deductcode { get; set; }
        public int? Projectref { get; set; }
        public string Name4 { get; set; }
        public double? Qprodsubamnt { get; set; }
        public int? Qprodsubuom { get; set; }
        public short? Qprodsubsrcindex { get; set; }
        public short? Qprodsubdepart { get; set; }
        public double? Pordamnttolerance { get; set; }
        public double? Sordamnttolerance { get; set; }
        public short? Multiaddtax { get; set; }
        public string Cpacode { get; set; }
        public int? Publiccountryref { get; set; }
        public string Fausefullifecode { get; set; }
        public string Fausefullifecode2 { get; set; }
        public short? Mold { get; set; }
        public short? Moldlifetracktype { get; set; }
        public double? Moldusagelife { get; set; }
        public short? Moldfactor { get; set; }
        public int? Moldmaintnumber { get; set; }
        public short? Moldmaintlifetype { get; set; }
        public double? Moldmaintlife { get; set; }
        public short? Moldlifeasratio { get; set; }
        public short? Moldmainttype { get; set; }
        public DateTime? Moldmaintbegdate { get; set; }
        public double? Moldmaintperiod { get; set; }
        public short? Moldmaintperunit { get; set; }
        public short? Obtaintype { get; set; }
        public short? Gaintype { get; set; }
        public string Forecastcode { get; set; }
        public double? Saleslimitquantity { get; set; }
        public short? Nodiscount { get; set; }
        public short? Levelcontrol { get; set; }
        public int? Notifycrdref { get; set; }
        public short? Uetdstransporttype { get; set; }
        public string Uetdsloadtype { get; set; }
        public string Uetdsloadtypedef { get; set; }
        public short? Uetdstransportmode { get; set; }
        public string Uetdsuncode { get; set; }
        public string Uetdsundef { get; set; }
        public string Uetdsloadunit { get; set; }
        public string Tsenr { get; set; }
    }
}
