using System;
using System.Collections.Generic;

#nullable disable

namespace Layer.Core.Models
{
    public partial class Lg001Faregist
    {
        public int Logicalref { get; set; }
        public string Regcode { get; set; }
        public short? Branch { get; set; }
        public short? Department { get; set; }
        public short? Transfer { get; set; }
        public int? Crdref { get; set; }
        public int? Ficheref { get; set; }
        public DateTime? Datein { get; set; }
        public DateTime? Dateofdepr { get; set; }
        public double? Quantity { get; set; }
        public double? Totout { get; set; }
        public double? Invalue { get; set; }
        public double? Vatamount { get; set; }
        public short? Vatdur { get; set; }
        public double? Deprrate { get; set; }
        public short? Deprdur { get; set; }
        public short? Deprtype { get; set; }
        public short? Revflag { get; set; }
        public short? Revdepflag { get; set; }
        public short? Partdep { get; set; }
        public short? Cancelled { get; set; }
        public double? Reportrate { get; set; }
        public double? Invaluex { get; set; }
        public double? Exptotal { get; set; }
        public double? Accumdepr { get; set; }
        public double? Accumreval { get; set; }
        public double? Exptotalx { get; set; }
        public double? Accumdeprx { get; set; }
        public double? Accumrevalx { get; set; }
        public short? Deprtype2 { get; set; }
        public double? Deprrate2 { get; set; }
        public short? Deprdur2 { get; set; }
        public short? Revalflag2 { get; set; }
        public short? Revdeprflag2 { get; set; }
        public double? Begreval { get; set; }
        public double? Begdepr { get; set; }
        public double? Begrevdepr { get; set; }
        public double? Begrevalx { get; set; }
        public double? Begdeprx { get; set; }
        public double? Begrevdeprx { get; set; }
        public double? OpvalsBegreval { get; set; }
        public double? OpvalsBegdepr { get; set; }
        public double? OpvalsBegrevdepr { get; set; }
        public double? OpvalsxBegreval { get; set; }
        public double? OpvalsxBegdepr { get; set; }
        public double? OpvalsxBegrevdepr { get; set; }
        public int? Dateofdepr2 { get; set; }
        public short? Partdep2 { get; set; }
        public short? Siteid { get; set; }
        public short? Recstatus { get; set; }
        public int? Orglogicref { get; set; }
        public short? Deprtype3 { get; set; }
        public double? Deprrate3 { get; set; }
        public short? Deprdur3 { get; set; }
        public short? Partdep3 { get; set; }
        public DateTime? Dateofdepr3 { get; set; }
        public double? OpvalsinfBegreval { get; set; }
        public double? OpvalsinfBegdepr { get; set; }
        public double? OpvalsinfBegrevdepr { get; set; }
        public double? OpvalsinfxBegreval { get; set; }
        public double? OpvalsinfxBegdepr { get; set; }
        public double? OpvalsinfxBegrevdepr { get; set; }
        public double? Diffprice { get; set; }
        public double? Diffrepprice { get; set; }
        public double? Infidx { get; set; }
        public short? Invdiscincl { get; set; }
        public double? Invdiscrate { get; set; }
        public short? Annualdistval { get; set; }
        public double? Inflbasedvalue { get; set; }
        public string Regdefinition { get; set; }
        public short? Deprtype4 { get; set; }
        public double? Deprrate4 { get; set; }
        public short? Deprdur4 { get; set; }
        public short? Partdep4 { get; set; }
        public DateTime? Dateofdepr4 { get; set; }
        public double? Opvalsinf2Begreval { get; set; }
        public double? Opvalsinf2Begdepr { get; set; }
        public double? Opvalsinf2Begrevdepr { get; set; }
        public double? Opvalsinfx2Begreval { get; set; }
        public double? Opvalsinfx2Begdepr { get; set; }
        public double? Opvalsinfx2Begrevdepr { get; set; }
        public double? Infidx2 { get; set; }
        public short? Annualdistval2 { get; set; }
        public double? Inflbasedvalue2 { get; set; }
        public DateTime? Dateactive { get; set; }
        public double? Taxexprate2 { get; set; }
        public short? Taxaccflag { get; set; }
        public int? Accficheref { get; set; }
        public string Regtypcod { get; set; }
        public string Regtypdef { get; set; }
        public string Regexpenscod { get; set; }
        public string Regexpensdef { get; set; }
        public short? Deprstpreasn { get; set; }
        public DateTime? Deprstpdate { get; set; }
        public double? Prodcapacity { get; set; }
        public string Capacityunit { get; set; }
        public short? Taxexptyp2 { get; set; }
        public short? Currtype { get; set; }
        public string Cyphcode { get; set; }
        public short? Approve { get; set; }
        public DateTime? Approvedate { get; set; }
        public int? Dateofdepr5 { get; set; }
        public double? Deprrate5 { get; set; }
        public short? Deprdur5 { get; set; }
        public short? Deprtype5 { get; set; }
        public short? Revalflag5 { get; set; }
        public short? Revdeprflag5 { get; set; }
        public short? Partdep5 { get; set; }
        public double? Opvalsinf3Begreval { get; set; }
        public double? Opvalsinf3Begdepr { get; set; }
        public double? Opvalsinf3Begrevdepr { get; set; }
        public double? Opvalsinfx3Begreval { get; set; }
        public double? Opvalsinfx3Begdepr { get; set; }
        public double? Opvalsinfx3Begrevdepr { get; set; }
        public short? Deprdurtype2 { get; set; }
        public short? CapiblockCreatedby { get; set; }
        public DateTime? CapiblockCreadeddate { get; set; }
        public short? CapiblockCreatedhour { get; set; }
        public short? CapiblockCreatedmin { get; set; }
        public short? CapiblockCreatedsec { get; set; }
        public short? CapiblockModifiedby { get; set; }
        public DateTime? CapiblockModifieddate { get; set; }
        public short? CapiblockModifiedhour { get; set; }
        public short? CapiblockModifiedmin { get; set; }
        public short? CapiblockModifiedsec { get; set; }
        public int? Projectref { get; set; }
        public short? Deprdurtype5 { get; set; }
        public double? Tfrsvalue { get; set; }
        public short? Sourceindex { get; set; }
        public string Guid { get; set; }
        public int? Centerref { get; set; }
        public string Fausefullifecode { get; set; }
        public string Fausefullifecode2 { get; set; }
        public string Fausefullifecode3 { get; set; }
        public string Fausefullifecode4 { get; set; }
        public string Fausefullifecode5 { get; set; }
        public double? Totrevamount { get; set; }
        public double? Totrevamountx { get; set; }
        public double? Figscostop { get; set; }
        public double? Figscostopx { get; set; }
        public int? Wsref { get; set; }
        public short? Maintlifetracktype { get; set; }
        public double? Maintusagelife { get; set; }
        public short? Maintfactor { get; set; }
        public int? Maintnumber { get; set; }
        public short? Maintlifetype { get; set; }
        public double? Maintlife { get; set; }
        public short? Maintlifeasratio { get; set; }
        public short? Mainttype { get; set; }
        public DateTime? Maintbegdate { get; set; }
        public double? Maintperiod { get; set; }
        public short? Maintperunit { get; set; }
        public double? Otvamount { get; set; }
        public double? Figstotcost { get; set; }
        public double? Figstotcostx { get; set; }
    }
}
