using System;
using System.Collections.Generic;

#nullable disable

namespace Layer.Core.Models
{
    public partial class Lg001Prodord
    {
        public int Logicalref { get; set; }
        public short? Fichetype { get; set; }
        public string Ficheno { get; set; }
        public DateTime? Date { get; set; }
        public string Genexp1 { get; set; }
        public string Genexp2 { get; set; }
        public string Genexp3 { get; set; }
        public string Genexp4 { get; set; }
        public string Genexp5 { get; set; }
        public string Genexp6 { get; set; }
        public short? Released { get; set; }
        public short? Cancelled { get; set; }
        public short? Priority { get; set; }
        public short? Method { get; set; }
        public short? Scheduled { get; set; }
        public short? Partialdel { get; set; }
        public short? Diffwhouseuse { get; set; }
        public short? Automtrissue { get; set; }
        public short? Rework { get; set; }
        public int? Routingref { get; set; }
        public int? Masterref { get; set; }
        public int? Revref { get; set; }
        public short? Factorynr { get; set; }
        public string Specode { get; set; }
        public string Cyphcode { get; set; }
        public int? Clientref { get; set; }
        public int? Accountref { get; set; }
        public int? Centerref { get; set; }
        public int? Itemref { get; set; }
        public int? Uomref { get; set; }
        public int? Usetref { get; set; }
        public double? Uinfo1 { get; set; }
        public double? Uinfo2 { get; set; }
        public double? Uinfo3 { get; set; }
        public double? Uinfo4 { get; set; }
        public double? Uinfo5 { get; set; }
        public double? Uinfo6 { get; set; }
        public double? Uinfo7 { get; set; }
        public double? Uinfo8 { get; set; }
        public double? Plnamount { get; set; }
        public double? Actamount { get; set; }
        public DateTime? Begdate { get; set; }
        public DateTime? Enddate { get; set; }
        public DateTime? Duedate { get; set; }
        public DateTime? Stopdate { get; set; }
        public DateTime? Startdate { get; set; }
        public DateTime? Plnbegdate { get; set; }
        public DateTime? Plnenddate { get; set; }
        public double? Plnduration { get; set; }
        public DateTime? Actbegdate { get; set; }
        public DateTime? Actenddate { get; set; }
        public double? Actduration { get; set; }
        public short? Status { get; set; }
        public double? Stdmaterialcost { get; set; }
        public double? Stdequiptcost { get; set; }
        public double? Stdwscost { get; set; }
        public double? Stdlaborcost { get; set; }
        public double? Stdoverhcost { get; set; }
        public double? Stdtotalcost { get; set; }
        public double? Stdmaterialrpcost { get; set; }
        public double? Stdequiptrpcost { get; set; }
        public double? Stdwsrpcost { get; set; }
        public double? Stdlaborrpcost { get; set; }
        public double? Stdoverhrpcost { get; set; }
        public double? Stdtotalrpcost { get; set; }
        public double? Actmaterialcost { get; set; }
        public double? Actequiptcost { get; set; }
        public double? Actwscost { get; set; }
        public double? Actlaborcost { get; set; }
        public double? Actoverhcost { get; set; }
        public double? Acttotalcost { get; set; }
        public double? Actmaterialrpcost { get; set; }
        public double? Actequiptrpcost { get; set; }
        public double? Actwsrpcost { get; set; }
        public double? Actlaborrpcost { get; set; }
        public double? Actoverhrpcost { get; set; }
        public double? Acttotalrpcost { get; set; }
        public short? Approved { get; set; }
        public short? Active { get; set; }
        public short? CapiblockCreatedby { get; set; }
        public DateTime? CapiblockCreadeddate { get; set; }
        public short? CapiblockCreatedhour { get; set; }
        public short? CapiblockCreatedmin { get; set; }
        public short? CapiblockCreatedsec { get; set; }
        public short? CapiblockModifiedby { get; set; }
        public DateTime? CapiblockModifieddate { get; set; }
        public short? CapiblockModifiedhour { get; set; }
        public short? CapiblockModifiedmin { get; set; }
        public short? CapiblockModifiedsec { get; set; }
        public short? Siteid { get; set; }
        public short? Recstatus { get; set; }
        public int? Orglogicref { get; set; }
        public int? Wfstatus { get; set; }
        public short? Needrelease { get; set; }
        public short? Needprocure { get; set; }
        public short? Procured { get; set; }
        public int? Begtime { get; set; }
        public int? Endtime { get; set; }
        public int? Plnbegtime { get; set; }
        public int? Plnendtime { get; set; }
        public int? Actbegtime { get; set; }
        public int? Actendtime { get; set; }
        public short? Printcnt { get; set; }
        public short? Stdaccounted { get; set; }
        public short? Actaccounted { get; set; }
        public double? Grossuinfo1 { get; set; }
        public double? Grossuinfo2 { get; set; }
        public short? Textinc { get; set; }
        public short? Chkrescap { get; set; }
        public int? Projectref { get; set; }
        public short? Advicews { get; set; }
        public int? Duetime { get; set; }
        public short? Approve { get; set; }
        public DateTime? Approvedate { get; set; }
        public double? Ufrsmaterialcost { get; set; }
        public double? Ufrsequiptcost { get; set; }
        public double? Ufrswscost { get; set; }
        public double? Ufrslaborcost { get; set; }
        public double? Ufrsoverhcost { get; set; }
        public double? Ufrstotalcost { get; set; }
        public double? Ufrsmaterialrpcost { get; set; }
        public double? Ufrsequiptrpcost { get; set; }
        public double? Ufrswsrpcost { get; set; }
        public double? Ufrslaborrpcost { get; set; }
        public double? Ufrsoverhrpcost { get; set; }
        public double? Ufrstotalrpcost { get; set; }
        public short? Ufrsaccounted { get; set; }
        public double? Stdoverhcostg1 { get; set; }
        public double? Stdoverhcostg2 { get; set; }
        public double? Stdoverhcostg3 { get; set; }
        public double? Stdoverhcostg4 { get; set; }
        public double? Stdoverhcostg5 { get; set; }
        public double? Stdoverhcostg6 { get; set; }
        public double? Stdoverhcostg7 { get; set; }
        public double? Stdoverhcostg8 { get; set; }
        public double? Stdoverhcostg9 { get; set; }
        public double? Stdoverhcostg10 { get; set; }
        public double? Stdoverhrpcostg1 { get; set; }
        public double? Stdoverhrpcostg2 { get; set; }
        public double? Stdoverhrpcostg3 { get; set; }
        public double? Stdoverhrpcostg4 { get; set; }
        public double? Stdoverhrpcostg5 { get; set; }
        public double? Stdoverhrpcostg6 { get; set; }
        public double? Stdoverhrpcostg7 { get; set; }
        public double? Stdoverhrpcostg8 { get; set; }
        public double? Stdoverhrpcostg9 { get; set; }
        public double? Stdoverhrpcostg10 { get; set; }
        public double? Actoverhcostg1 { get; set; }
        public double? Actoverhcostg2 { get; set; }
        public double? Actoverhcostg3 { get; set; }
        public double? Actoverhcostg4 { get; set; }
        public double? Actoverhcostg5 { get; set; }
        public double? Actoverhcostg6 { get; set; }
        public double? Actoverhcostg7 { get; set; }
        public double? Actoverhcostg8 { get; set; }
        public double? Actoverhcostg9 { get; set; }
        public double? Actoverhcostg10 { get; set; }
        public double? Actoverhrpcostg1 { get; set; }
        public double? Actoverhrpcostg2 { get; set; }
        public double? Actoverhrpcostg3 { get; set; }
        public double? Actoverhrpcostg4 { get; set; }
        public double? Actoverhrpcostg5 { get; set; }
        public double? Actoverhrpcostg6 { get; set; }
        public double? Actoverhrpcostg7 { get; set; }
        public double? Actoverhrpcostg8 { get; set; }
        public double? Actoverhrpcostg9 { get; set; }
        public double? Actoverhrpcostg10 { get; set; }
        public double? Ufrsoverhcostg1 { get; set; }
        public double? Ufrsoverhcostg2 { get; set; }
        public double? Ufrsoverhcostg3 { get; set; }
        public double? Ufrsoverhcostg4 { get; set; }
        public double? Ufrsoverhcostg5 { get; set; }
        public double? Ufrsoverhcostg6 { get; set; }
        public double? Ufrsoverhcostg7 { get; set; }
        public double? Ufrsoverhcostg8 { get; set; }
        public double? Ufrsoverhcostg9 { get; set; }
        public double? Ufrsoverhcostg10 { get; set; }
        public double? Ufrsoverhrpcostg1 { get; set; }
        public double? Ufrsoverhrpcostg2 { get; set; }
        public double? Ufrsoverhrpcostg3 { get; set; }
        public double? Ufrsoverhrpcostg4 { get; set; }
        public double? Ufrsoverhrpcostg5 { get; set; }
        public double? Ufrsoverhrpcostg6 { get; set; }
        public double? Ufrsoverhrpcostg7 { get; set; }
        public double? Ufrsoverhrpcostg8 { get; set; }
        public double? Ufrsoverhrpcostg9 { get; set; }
        public double? Ufrsoverhrpcostg10 { get; set; }
        public double? Rollupmaterialcost { get; set; }
        public double? Rollupequiptcost { get; set; }
        public double? Rollupwscost { get; set; }
        public double? Rolluplaborcost { get; set; }
        public double? Rollupoverhcost { get; set; }
        public double? Rolluptotalcost { get; set; }
        public double? Rollupmaterialrpcost { get; set; }
        public double? Rollupequiptrpcost { get; set; }
        public double? Rollupwsrpcost { get; set; }
        public double? Rolluplaborrpcost { get; set; }
        public double? Rollupoverhrpcost { get; set; }
        public double? Rolluptotalrpcost { get; set; }
        public double? Rollupoverhcostg1 { get; set; }
        public double? Rollupoverhcostg2 { get; set; }
        public double? Rollupoverhcostg3 { get; set; }
        public double? Rollupoverhcostg4 { get; set; }
        public double? Rollupoverhcostg5 { get; set; }
        public double? Rollupoverhcostg6 { get; set; }
        public double? Rollupoverhcostg7 { get; set; }
        public double? Rollupoverhcostg8 { get; set; }
        public double? Rollupoverhcostg9 { get; set; }
        public double? Rollupoverhcostg10 { get; set; }
        public double? Rollupoverhrpcostg1 { get; set; }
        public double? Rollupoverhrpcostg2 { get; set; }
        public double? Rollupoverhrpcostg3 { get; set; }
        public double? Rollupoverhrpcostg4 { get; set; }
        public double? Rollupoverhrpcostg5 { get; set; }
        public double? Rollupoverhrpcostg6 { get; set; }
        public double? Rollupoverhrpcostg7 { get; set; }
        public double? Rollupoverhrpcostg8 { get; set; }
        public double? Rollupoverhrpcostg9 { get; set; }
        public double? Rollupoverhrpcostg10 { get; set; }
        public short? Doplnreserve { get; set; }
        public short? Actcostcalculated { get; set; }
        public short? Hasparallelwsload { get; set; }
        public string Guid { get; set; }
        public short? Createwhfiche { get; set; }
        public DateTime? Printdate { get; set; }
        public short? Doslplnreserve { get; set; }
    }
}
