using System;
using System.Collections.Generic;

#nullable disable

namespace Layer.Core.Models
{
    public partial class Lg001Displine
    {
        public int Logicalref { get; set; }
        public int? Prodordref { get; set; }
        public short? Bomlevel { get; set; }
        public int? Revref { get; set; }
        public string Lineno { get; set; }
        public int? Routlineref { get; set; }
        public int? Operationref { get; set; }
        public short? Qcopok { get; set; }
        public int? Opreqref { get; set; }
        public int? Wsref { get; set; }
        public double? Wsdailyoptime { get; set; }
        public short? Wsworkingdays { get; set; }
        public short? Scheduled { get; set; }
        public short? Released { get; set; }
        public int? Setuptime { get; set; }
        public int? Queuetime { get; set; }
        public double? Runbatch { get; set; }
        public int? Runtime { get; set; }
        public double? Movebatch { get; set; }
        public int? Movetime { get; set; }
        public int? Insptime { get; set; }
        public int? Headtime { get; set; }
        public int? Tailtime { get; set; }
        public DateTime? Opbegdate { get; set; }
        public int? Opbegtime { get; set; }
        public DateTime? Opduedate { get; set; }
        public int? Opduetime { get; set; }
        public double? Plnduration { get; set; }
        public DateTime? Actbegdate { get; set; }
        public int? Actbegtime { get; set; }
        public DateTime? Actduedate { get; set; }
        public int? Actduetime { get; set; }
        public double? Actduration { get; set; }
        public short? Linestatus { get; set; }
        public double? Stdmaterialcost { get; set; }
        public double? Stdequiptcost { get; set; }
        public double? Stdwscost { get; set; }
        public double? Stdlaborcost { get; set; }
        public double? Stdoverhcost { get; set; }
        public double? Stdtotalcost { get; set; }
        public double? Stdmaterialrpcost { get; set; }
        public double? Stdequiptrpcost { get; set; }
        public double? Stdwsrpcost { get; set; }
        public double? Stdlaborrpcost { get; set; }
        public double? Stdoverhrpcost { get; set; }
        public double? Stdtotalrpcost { get; set; }
        public double? Actmaterialcost { get; set; }
        public double? Actequiptcost { get; set; }
        public double? Actwscost { get; set; }
        public double? Actlaborcost { get; set; }
        public double? Actoverhcost { get; set; }
        public double? Acttotalcost { get; set; }
        public double? Actmaterialrpcost { get; set; }
        public double? Actequiptrpcost { get; set; }
        public double? Actwsrpcost { get; set; }
        public double? Actlaborrpcost { get; set; }
        public double? Actoverhrpcost { get; set; }
        public double? Acttotalrpcost { get; set; }
        public string Stdovhdformula { get; set; }
        public string Stdovhdrpformula { get; set; }
        public string Actovhdformula { get; set; }
        public string Actovhdrpformula { get; set; }
        public int? Itemref { get; set; }
        public DateTime? Opwsbegdate { get; set; }
        public int? Bommasterref { get; set; }
        public double? Stpduration { get; set; }
        public double? Stpcostduration { get; set; }
        public string Docode { get; set; }
        public string Specode { get; set; }
        public string Cyphcode { get; set; }
        public short? Siteid { get; set; }
        public short? Recstatus { get; set; }
        public int? Orglogicref { get; set; }
        public int? Wfstatus { get; set; }
        public short? Printcnt { get; set; }
        public int? Projectref { get; set; }
        public short? Docounting { get; set; }
        public int? Variantref { get; set; }
        public double? Ufrsmaterialcost { get; set; }
        public double? Ufrsequiptcost { get; set; }
        public double? Ufrswscost { get; set; }
        public double? Ufrslaborcost { get; set; }
        public double? Ufrsoverhcost { get; set; }
        public double? Ufrstotalcost { get; set; }
        public double? Ufrsmaterialrpcost { get; set; }
        public double? Ufrsequiptrpcost { get; set; }
        public double? Ufrswsrpcost { get; set; }
        public double? Ufrslaborrpcost { get; set; }
        public double? Ufrsoverhrpcost { get; set; }
        public double? Ufrstotalrpcost { get; set; }
        public double? Stdoverhcostg1 { get; set; }
        public double? Stdoverhcostg2 { get; set; }
        public double? Stdoverhcostg3 { get; set; }
        public double? Stdoverhcostg4 { get; set; }
        public double? Stdoverhcostg5 { get; set; }
        public double? Stdoverhcostg6 { get; set; }
        public double? Stdoverhcostg7 { get; set; }
        public double? Stdoverhcostg8 { get; set; }
        public double? Stdoverhcostg9 { get; set; }
        public double? Stdoverhcostg10 { get; set; }
        public double? Stdoverhrpcostg1 { get; set; }
        public double? Stdoverhrpcostg2 { get; set; }
        public double? Stdoverhrpcostg3 { get; set; }
        public double? Stdoverhrpcostg4 { get; set; }
        public double? Stdoverhrpcostg5 { get; set; }
        public double? Stdoverhrpcostg6 { get; set; }
        public double? Stdoverhrpcostg7 { get; set; }
        public double? Stdoverhrpcostg8 { get; set; }
        public double? Stdoverhrpcostg9 { get; set; }
        public double? Stdoverhrpcostg10 { get; set; }
        public double? Actoverhcostg1 { get; set; }
        public double? Actoverhcostg2 { get; set; }
        public double? Actoverhcostg3 { get; set; }
        public double? Actoverhcostg4 { get; set; }
        public double? Actoverhcostg5 { get; set; }
        public double? Actoverhcostg6 { get; set; }
        public double? Actoverhcostg7 { get; set; }
        public double? Actoverhcostg8 { get; set; }
        public double? Actoverhcostg9 { get; set; }
        public double? Actoverhcostg10 { get; set; }
        public double? Actoverhrpcostg1 { get; set; }
        public double? Actoverhrpcostg2 { get; set; }
        public double? Actoverhrpcostg3 { get; set; }
        public double? Actoverhrpcostg4 { get; set; }
        public double? Actoverhrpcostg5 { get; set; }
        public double? Actoverhrpcostg6 { get; set; }
        public double? Actoverhrpcostg7 { get; set; }
        public double? Actoverhrpcostg8 { get; set; }
        public double? Actoverhrpcostg9 { get; set; }
        public double? Actoverhrpcostg10 { get; set; }
        public double? Ufrsoverhcostg1 { get; set; }
        public double? Ufrsoverhcostg2 { get; set; }
        public double? Ufrsoverhcostg3 { get; set; }
        public double? Ufrsoverhcostg4 { get; set; }
        public double? Ufrsoverhcostg5 { get; set; }
        public double? Ufrsoverhcostg6 { get; set; }
        public double? Ufrsoverhcostg7 { get; set; }
        public double? Ufrsoverhcostg8 { get; set; }
        public double? Ufrsoverhcostg9 { get; set; }
        public double? Ufrsoverhcostg10 { get; set; }
        public double? Ufrsoverhrpcostg1 { get; set; }
        public double? Ufrsoverhrpcostg2 { get; set; }
        public double? Ufrsoverhrpcostg3 { get; set; }
        public double? Ufrsoverhrpcostg4 { get; set; }
        public double? Ufrsoverhrpcostg5 { get; set; }
        public double? Ufrsoverhrpcostg6 { get; set; }
        public double? Ufrsoverhrpcostg7 { get; set; }
        public double? Ufrsoverhrpcostg8 { get; set; }
        public double? Ufrsoverhrpcostg9 { get; set; }
        public double? Ufrsoverhrpcostg10 { get; set; }
        public double? Rollupmaterialcost { get; set; }
        public double? Rollupequiptcost { get; set; }
        public double? Rollupwscost { get; set; }
        public double? Rolluplaborcost { get; set; }
        public double? Rollupoverhcost { get; set; }
        public double? Rolluptotalcost { get; set; }
        public double? Rollupmaterialrpcost { get; set; }
        public double? Rollupequiptrpcost { get; set; }
        public double? Rollupwsrpcost { get; set; }
        public double? Rolluplaborrpcost { get; set; }
        public double? Rollupoverhrpcost { get; set; }
        public double? Rolluptotalrpcost { get; set; }
        public double? Rollupoverhcostg1 { get; set; }
        public double? Rollupoverhcostg2 { get; set; }
        public double? Rollupoverhcostg3 { get; set; }
        public double? Rollupoverhcostg4 { get; set; }
        public double? Rollupoverhcostg5 { get; set; }
        public double? Rollupoverhcostg6 { get; set; }
        public double? Rollupoverhcostg7 { get; set; }
        public double? Rollupoverhcostg8 { get; set; }
        public double? Rollupoverhcostg9 { get; set; }
        public double? Rollupoverhcostg10 { get; set; }
        public double? Rollupoverhrpcostg1 { get; set; }
        public double? Rollupoverhrpcostg2 { get; set; }
        public double? Rollupoverhrpcostg3 { get; set; }
        public double? Rollupoverhrpcostg4 { get; set; }
        public double? Rollupoverhrpcostg5 { get; set; }
        public double? Rollupoverhrpcostg6 { get; set; }
        public double? Rollupoverhrpcostg7 { get; set; }
        public double? Rollupoverhrpcostg8 { get; set; }
        public double? Rollupoverhrpcostg9 { get; set; }
        public double? Rollupoverhrpcostg10 { get; set; }
        public string Guid { get; set; }
        public double? Waitbatch { get; set; }
        public int? Waittime { get; set; }
        public short? Prodordtyp { get; set; }
        public int? Clientref { get; set; }
        public short? Manueledit { get; set; }
        public short? Rework { get; set; }
        public short? Parting { get; set; }
        public DateTime? Printdate { get; set; }
        public short? Entrytype { get; set; }
    }
}
