using System;
using System.Collections.Generic;

#nullable disable

namespace Layer.Core.Models
{
    public partial class Lg001Clcard
    {
        public int Logicalref { get; set; }
        public short? Active { get; set; }
        public short? Cardtype { get; set; }
        public string Code { get; set; }
        public string Definition { get; set; }
        public string Specode { get; set; }
        public string Cyphcode { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Postcode { get; set; }
        public string Telnrs1 { get; set; }
        public string Telnrs2 { get; set; }
        public string Faxnr { get; set; }
        public string Taxnr { get; set; }
        public string Taxoffice { get; set; }
        public string Incharge { get; set; }
        public double? Discrate { get; set; }
        public int? Extenref { get; set; }
        public int? Paymentref { get; set; }
        public string Emailaddr { get; set; }
        public string Webaddr { get; set; }
        public short? Warnmethod { get; set; }
        public string Warnemailaddr { get; set; }
        public string Warnfaxnr { get; set; }
        public short? Clanguage { get; set; }
        public string Vatnr { get; set; }
        public short? Blocked { get; set; }
        public string Bankbranchs1 { get; set; }
        public string Bankbranchs2 { get; set; }
        public string Bankbranchs3 { get; set; }
        public string Bankbranchs4 { get; set; }
        public string Bankbranchs5 { get; set; }
        public string Bankbranchs6 { get; set; }
        public string Bankbranchs7 { get; set; }
        public string Bankaccounts1 { get; set; }
        public string Bankaccounts2 { get; set; }
        public string Bankaccounts3 { get; set; }
        public string Bankaccounts4 { get; set; }
        public string Bankaccounts5 { get; set; }
        public string Bankaccounts6 { get; set; }
        public string Bankaccounts7 { get; set; }
        public string Deliverymethod { get; set; }
        public string Deliveryfirm { get; set; }
        public short? Ccurrency { get; set; }
        public short? Textinc { get; set; }
        public short? Siteid { get; set; }
        public short? Recstatus { get; set; }
        public int? Orglogicref { get; set; }
        public string Edino { get; set; }
        public string Tradinggrp { get; set; }
        public short? CapiblockCreatedby { get; set; }
        public DateTime? CapiblockCreadeddate { get; set; }
        public short? CapiblockCreatedhour { get; set; }
        public short? CapiblockCreatedmin { get; set; }
        public short? CapiblockCreatedsec { get; set; }
        public short? CapiblockModifiedby { get; set; }
        public DateTime? CapiblockModifieddate { get; set; }
        public short? CapiblockModifiedhour { get; set; }
        public short? CapiblockModifiedmin { get; set; }
        public short? CapiblockModifiedsec { get; set; }
        public short? Paymentproc { get; set; }
        public short? Cratediffproc { get; set; }
        public int? Wfstatus { get; set; }
        public string Ppgroupcode { get; set; }
        public int? Ppgroupref { get; set; }
        public string Taxoffcode { get; set; }
        public string Towncode { get; set; }
        public string Town { get; set; }
        public string Districtcode { get; set; }
        public string District { get; set; }
        public string Citycode { get; set; }
        public string Countrycode { get; set; }
        public short? Ordsendmethod { get; set; }
        public string Ordsendemailaddr { get; set; }
        public string Ordsendfaxnr { get; set; }
        public short? Dspsendmethod { get; set; }
        public string Dspsendemailaddr { get; set; }
        public string Dspsendfaxnr { get; set; }
        public short? Invsendmethod { get; set; }
        public string Invsendemailaddr { get; set; }
        public string Invsendfaxnr { get; set; }
        public short? Subscriberstat { get; set; }
        public string Subscriberext { get; set; }
        public string Autopaidbank { get; set; }
        public short? Paymenttype { get; set; }
        public int? Lastsendremlev { get; set; }
        public int? Extaccessflags { get; set; }
        public short? Ordsendformat { get; set; }
        public short? Dspsendformat { get; set; }
        public short? Invsendformat { get; set; }
        public short? Remsendformat { get; set; }
        public string Storecreditcardno { get; set; }
        public short? Clordfreq { get; set; }
        public short? Ordday { get; set; }
        public string Logoid { get; set; }
        public short? Lidconfirmed { get; set; }
        public string Expregno { get; set; }
        public string Expdocno { get; set; }
        public int? Expbustypref { get; set; }
        public short? Invprintcnt { get; set; }
        public short? Pieceordinflict { get; set; }
        public short? Collectinvoicing { get; set; }
        public short? Ebusdatasendtype { get; set; }
        public int? Inistatusflags { get; set; }
        public short? Slsorderstatus { get; set; }
        public short? Slsorderprice { get; set; }
        public short? Ltrsendmethod { get; set; }
        public string Ltrsendemailaddr { get; set; }
        public string Ltrsendfaxnr { get; set; }
        public short? Ltrsendformat { get; set; }
        public short? Imageinc { get; set; }
        public string Cellphone { get; set; }
        public short? Sameitemcodeuse { get; set; }
        public string Statecode { get; set; }
        public string Statename { get; set; }
        public int? Wflowcrdref { get; set; }
        public int? Parentclref { get; set; }
        public int? Lowlevelcodes1 { get; set; }
        public int? Lowlevelcodes2 { get; set; }
        public int? Lowlevelcodes3 { get; set; }
        public int? Lowlevelcodes4 { get; set; }
        public int? Lowlevelcodes5 { get; set; }
        public int? Lowlevelcodes6 { get; set; }
        public int? Lowlevelcodes7 { get; set; }
        public int? Lowlevelcodes8 { get; set; }
        public int? Lowlevelcodes9 { get; set; }
        public int? Lowlevelcodes10 { get; set; }
        public string Telcodes1 { get; set; }
        public string Telcodes2 { get; set; }
        public string Faxcode { get; set; }
        public short? Purchbrws { get; set; }
        public short? Salesbrws { get; set; }
        public short? Impbrws { get; set; }
        public short? Expbrws { get; set; }
        public short? Finbrws { get; set; }
        public string Orglogoid { get; set; }
        public short? Addtoreflist { get; set; }
        public short? Textreftr { get; set; }
        public short? Textrefen { get; set; }
        public short? Arpquoteinc { get; set; }
        public short? Clcrm { get; set; }
        public short? Grpfirmnr { get; set; }
        public int? Conscoderef { get; set; }
        public string Specode2 { get; set; }
        public string Specode3 { get; set; }
        public string Specode4 { get; set; }
        public string Specode5 { get; set; }
        public short? Offsendmethod { get; set; }
        public string Offsendemailaddr { get; set; }
        public string Offsendfaxnr { get; set; }
        public short? Offsendformat { get; set; }
        public short? Ebankno { get; set; }
        public short? Loangrpctrl { get; set; }
        public string Banknames1 { get; set; }
        public string Banknames2 { get; set; }
        public string Banknames3 { get; set; }
        public string Banknames4 { get; set; }
        public string Banknames5 { get; set; }
        public string Banknames6 { get; set; }
        public string Banknames7 { get; set; }
        public short? Ldxfirmnr { get; set; }
        public string Mapid { get; set; }
        public string Longitude { get; set; }
        public string Latitute { get; set; }
        public string Cityid { get; set; }
        public string Townid { get; set; }
        public string Bankibans1 { get; set; }
        public string Bankibans2 { get; set; }
        public string Bankibans3 { get; set; }
        public string Bankibans4 { get; set; }
        public string Bankibans5 { get; set; }
        public string Bankibans6 { get; set; }
        public string Bankibans7 { get; set; }
        public string Tckno { get; set; }
        public short? Isperscomp { get; set; }
        public short? Extsendmethod { get; set; }
        public string Extsendemailaddr { get; set; }
        public string Extsendfaxnr { get; set; }
        public short? Extsendformat { get; set; }
        public string Bankbics1 { get; set; }
        public string Bankbics2 { get; set; }
        public string Bankbics3 { get; set; }
        public string Bankbics4 { get; set; }
        public string Bankbics5 { get; set; }
        public string Bankbics6 { get; set; }
        public string Bankbics7 { get; set; }
        public int? Cashref { get; set; }
        public short? Usedinperiods { get; set; }
        public string Incharge2 { get; set; }
        public string Incharge3 { get; set; }
        public string Emailaddr2 { get; set; }
        public string Emailaddr3 { get; set; }
        public short? Rsklimcr { get; set; }
        public short? Rskduedatecr { get; set; }
        public short? Rskagingcr { get; set; }
        public short? Rskagingday { get; set; }
        public short? Accepteinv { get; set; }
        public string Einvoiceid { get; set; }
        public short? Profileid { get; set; }
        public string Bankbcurrency1 { get; set; }
        public string Bankbcurrency2 { get; set; }
        public string Bankbcurrency3 { get; set; }
        public string Bankbcurrency4 { get; set; }
        public string Bankbcurrency5 { get; set; }
        public string Bankbcurrency6 { get; set; }
        public string Bankbcurrency7 { get; set; }
        public short? Purcorderstatus { get; set; }
        public short? Purcorderprice { get; set; }
        public short? Isforeign { get; set; }
        public int? Shipbegtime1 { get; set; }
        public int? Shipbegtime2 { get; set; }
        public int? Shipbegtime3 { get; set; }
        public int? Shipendtime1 { get; set; }
        public int? Shipendtime2 { get; set; }
        public int? Shipendtime3 { get; set; }
        public double? Dbslimit1 { get; set; }
        public double? Dbslimit2 { get; set; }
        public double? Dbslimit3 { get; set; }
        public double? Dbslimit4 { get; set; }
        public double? Dbslimit5 { get; set; }
        public double? Dbslimit6 { get; set; }
        public double? Dbslimit7 { get; set; }
        public double? Dbstotal1 { get; set; }
        public double? Dbstotal2 { get; set; }
        public double? Dbstotal3 { get; set; }
        public double? Dbstotal4 { get; set; }
        public double? Dbstotal5 { get; set; }
        public double? Dbstotal6 { get; set; }
        public double? Dbstotal7 { get; set; }
        public short? Dbsbankno1 { get; set; }
        public short? Dbsbankno2 { get; set; }
        public short? Dbsbankno3 { get; set; }
        public short? Dbsbankno4 { get; set; }
        public short? Dbsbankno5 { get; set; }
        public short? Dbsbankno6 { get; set; }
        public short? Dbsbankno7 { get; set; }
        public short? Dbsriskcntrl1 { get; set; }
        public short? Dbsriskcntrl2 { get; set; }
        public short? Dbsriskcntrl3 { get; set; }
        public short? Dbsriskcntrl4 { get; set; }
        public short? Dbsriskcntrl5 { get; set; }
        public short? Dbsriskcntrl6 { get; set; }
        public short? Dbsriskcntrl7 { get; set; }
        public short? Dbsbankcurrency1 { get; set; }
        public short? Dbsbankcurrency2 { get; set; }
        public short? Dbsbankcurrency3 { get; set; }
        public short? Dbsbankcurrency4 { get; set; }
        public short? Dbsbankcurrency5 { get; set; }
        public short? Dbsbankcurrency6 { get; set; }
        public short? Dbsbankcurrency7 { get; set; }
        public string Bankcorrpacc1 { get; set; }
        public string Bankcorrpacc2 { get; set; }
        public string Bankcorrpacc3 { get; set; }
        public string Bankcorrpacc4 { get; set; }
        public string Bankcorrpacc5 { get; set; }
        public string Bankcorrpacc6 { get; set; }
        public string Bankcorrpacc7 { get; set; }
        public string Bankvoen1 { get; set; }
        public string Bankvoen2 { get; set; }
        public string Bankvoen3 { get; set; }
        public string Bankvoen4 { get; set; }
        public string Bankvoen5 { get; set; }
        public string Bankvoen6 { get; set; }
        public string Bankvoen7 { get; set; }
        public short? Einvoicetype { get; set; }
        public string Definition2 { get; set; }
        public string Telextnums1 { get; set; }
        public string Telextnums2 { get; set; }
        public string Faxextnum { get; set; }
        public string Facebookurl { get; set; }
        public string Twitterurl { get; set; }
        public string Appleid { get; set; }
        public string Skypeid { get; set; }
        public string Globalid { get; set; }
        public string Guid { get; set; }
        public short? Duedatecount { get; set; }
        public double? Duedatelimit { get; set; }
        public short? Duedatetrack { get; set; }
        public short? Duedatecontrol1 { get; set; }
        public short? Duedatecontrol2 { get; set; }
        public short? Duedatecontrol3 { get; set; }
        public short? Duedatecontrol4 { get; set; }
        public short? Duedatecontrol5 { get; set; }
        public short? Duedatecontrol6 { get; set; }
        public short? Duedatecontrol7 { get; set; }
        public short? Duedatecontrol8 { get; set; }
        public short? Duedatecontrol9 { get; set; }
        public short? Duedatecontrol10 { get; set; }
        public short? Duedatecontrol11 { get; set; }
        public short? Duedatecontrol12 { get; set; }
        public short? Duedatecontrol13 { get; set; }
        public short? Duedatecontrol14 { get; set; }
        public short? Duedatecontrol15 { get; set; }
        public string Adressno { get; set; }
        public string Postlabelcode { get; set; }
        public string Senderlabelcode { get; set; }
        public short? Closedatecount { get; set; }
        public short? Closedatetrack { get; set; }
        public short? Degactive { get; set; }
        public short? Degcurr { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public short? Labelinfo { get; set; }
        public int? Defbnaccref { get; set; }
        public int? Projectref { get; set; }
        public short? Disctype { get; set; }
        public short? Sendmod { get; set; }
        public short? Ispercurr { get; set; }
        public short? Curratetype { get; set; }
        public short? Insteadofdesp { get; set; }
        public short? Einvoicetyp { get; set; }
        public short? Fbssendmethod { get; set; }
        public string Fbssendemailaddr { get; set; }
        public short? Fbssendformat { get; set; }
        public string Fbssendfaxnr { get; set; }
        public short? Fbasendmethod { get; set; }
        public string Fbasendemailaddr { get; set; }
        public short? Fbasendformat { get; set; }
        public string Fbasendfaxnr { get; set; }
        public int? Sectormainref { get; set; }
        public int? Sectorsubref { get; set; }
        public short? Personelcosts { get; set; }
        public string Earcemailaddr1 { get; set; }
        public string Earcemailaddr2 { get; set; }
        public string Earcemailaddr3 { get; set; }
        public short? Factorydivnr { get; set; }
        public short? Factorynr { get; set; }
        public short? Ininvennr { get; set; }
        public short? Outinvennr { get; set; }
        public double? Qtydepduration { get; set; }
        public double? Qtyindepduration { get; set; }
        public short? Overlaptype { get; set; }
        public double? Overlapamnt { get; set; }
        public double? Overlapperc { get; set; }
        public short? Brokercomp { get; set; }
        public short? Createwhfiche { get; set; }
        public short? Einvcustom { get; set; }
        public short? Subcont { get; set; }
        public short? Ordpriority { get; set; }
        public short? Acceptedesp { get; set; }
        public short? Profileiddesp { get; set; }
        public short? Labelinfodesp { get; set; }
        public string Postlabelcodedesp { get; set; }
        public string Senderlabelcodedesp { get; set; }
        public short? Accepteinvpublic { get; set; }
        public int? Publicbnaccref { get; set; }
        public short? Paymentprocbranch { get; set; }
        public short? Kvkkpermstatus { get; set; }
        public DateTime? Kvkkbegdate { get; set; }
        public DateTime? Kvkkenddate { get; set; }
        public DateTime? Kvkkcanceldate { get; set; }
        public short? Kvkkanonystatus { get; set; }
        public DateTime? Kvkkanonydate { get; set; }
        public short? Eximsendmethod { get; set; }
        public string Eximsendemailaddr { get; set; }
        public short? Eximsendformat { get; set; }
        public string Eximsendfaxnr { get; set; }
        public short? Clccandeduct { get; set; }
        public int? Driverref { get; set; }
        public string Inchtelcodes1 { get; set; }
        public string Inchtelcodes2 { get; set; }
        public string Inchtelcodes3 { get; set; }
        public string Inchtelnrs1 { get; set; }
        public string Inchtelnrs2 { get; set; }
        public string Inchtelnrs3 { get; set; }
        public string Inchtelextnums1 { get; set; }
        public string Inchtelextnums2 { get; set; }
        public string Inchtelextnums3 { get; set; }
        public int? Notifycrdref { get; set; }
        public short? Excntrytyp { get; set; }
        public int? Excntryref { get; set; }
        public short? Imcntrytyp { get; set; }
        public int? Imcntryref { get; set; }
        public int? Eximpaytypref { get; set; }
        public int? Eximbrbankref { get; set; }
        public int? Eximcustomref { get; set; }
        public int? Eximregtypref { get; set; }
        public int? Eximntfyclref { get; set; }
        public int? Eximcnsltclref { get; set; }
        public int? Eximfrghtclref { get; set; }
        public short? Dispprintcnt { get; set; }
        public short? Ordprintcnt { get; set; }
    }
}
