using System;
using System.Collections.Generic;

#nullable disable

namespace Layer.Core.Models
{
    public partial class Lg00101Stline
    {
        public int Logicalref { get; set; }
        public int? Stockref { get; set; }
        public short? Linetype { get; set; }
        public int? Prevlineref { get; set; }
        public short? Prevlineno { get; set; }
        public short? Detline { get; set; }
        public short? Trcode { get; set; }
        public DateTime? Date { get; set; }
        public int? Ftime { get; set; }
        public short? Globtrans { get; set; }
        public short? Calctype { get; set; }
        public int? Prodorderref { get; set; }
        public short? Sourcetype { get; set; }
        public short? Sourceindex { get; set; }
        public short? Sourcecostgrp { get; set; }
        public int? Sourcewsref { get; set; }
        public int? Sourcepolnref { get; set; }
        public short? Desttype { get; set; }
        public short? Destindex { get; set; }
        public short? Destcostgrp { get; set; }
        public int? Destwsref { get; set; }
        public int? Destpolnref { get; set; }
        public short? Factorynr { get; set; }
        public short? Iocode { get; set; }
        public int? Stficheref { get; set; }
        public short? Stfichelnno { get; set; }
        public int? Invoiceref { get; set; }
        public short? Invoicelnno { get; set; }
        public int? Clientref { get; set; }
        public int? Ordtransref { get; set; }
        public int? Ordficheref { get; set; }
        public int? Centerref { get; set; }
        public int? Accountref { get; set; }
        public int? Vataccref { get; set; }
        public int? Vatcenterref { get; set; }
        public int? Praccref { get; set; }
        public int? Prcenterref { get; set; }
        public int? Prvataccref { get; set; }
        public int? Prvatcenref { get; set; }
        public int? Promref { get; set; }
        public int? Paydefref { get; set; }
        public string Specode { get; set; }
        public string Delvrycode { get; set; }
        public double? Amount { get; set; }
        public double? Price { get; set; }
        public double? Total { get; set; }
        public short? Prcurr { get; set; }
        public double? Prprice { get; set; }
        public short? Trcurr { get; set; }
        public double? Trrate { get; set; }
        public double? Reportrate { get; set; }
        public double? Distcost { get; set; }
        public double? Distdisc { get; set; }
        public double? Distexp { get; set; }
        public double? Distprom { get; set; }
        public double? Discper { get; set; }
        public string Lineexp { get; set; }
        public int? Uomref { get; set; }
        public int? Usref { get; set; }
        public double? Uinfo1 { get; set; }
        public double? Uinfo2 { get; set; }
        public double? Uinfo3 { get; set; }
        public double? Uinfo4 { get; set; }
        public double? Uinfo5 { get; set; }
        public double? Uinfo6 { get; set; }
        public double? Uinfo7 { get; set; }
        public double? Uinfo8 { get; set; }
        public double? Plnamount { get; set; }
        public short? Vatinc { get; set; }
        public double? Vat { get; set; }
        public double? Vatamnt { get; set; }
        public double? Vatmatrah { get; set; }
        public int? Billeditem { get; set; }
        public short? Billed { get; set; }
        public short? Cpstflag { get; set; }
        public short? Retcosttype { get; set; }
        public int? Sourcelink { get; set; }
        public double? Retcost { get; set; }
        public double? Retcostcurr { get; set; }
        public double? Outcost { get; set; }
        public double? Outcostcurr { get; set; }
        public double? Retamount { get; set; }
        public int? Faregref { get; set; }
        public short? Faattrib { get; set; }
        public short? Cancelled { get; set; }
        public double? Linenet { get; set; }
        public double? Distaddexp { get; set; }
        public int? Fadaccref { get; set; }
        public int? Fadcenterref { get; set; }
        public int? Faraccref { get; set; }
        public int? Farcenterref { get; set; }
        public double? Diffprice { get; set; }
        public double? Diffprcost { get; set; }
        public short? Decprdiff { get; set; }
        public short? Lprodstat { get; set; }
        public double? Prdexptotal { get; set; }
        public double? Diffrepprice { get; set; }
        public double? Diffprcrcost { get; set; }
        public int? Salesmanref { get; set; }
        public int? Faplaccref { get; set; }
        public int? Faplcenterref { get; set; }
        public string Outputidcode { get; set; }
        public int? Dref { get; set; }
        public double? Costrate { get; set; }
        public short? Xpriceupd { get; set; }
        public double? Xprice { get; set; }
        public double? Xreprate { get; set; }
        public double? Distcoef { get; set; }
        public short? Transqcok { get; set; }
        public short? Siteid { get; set; }
        public short? Recstatus { get; set; }
        public int? Orglogicref { get; set; }
        public int? Wfstatus { get; set; }
        public int? Polineref { get; set; }
        public int? Plnsttransref { get; set; }
        public short? Netdiscflag { get; set; }
        public double? Netdiscperc { get; set; }
        public double? Netdiscamnt { get; set; }
        public double? Vatcalcdiff { get; set; }
        public int? Conditionref { get; set; }
        public int? Distorderref { get; set; }
        public int? Distordlineref { get; set; }
        public int? Campaignrefs1 { get; set; }
        public int? Campaignrefs2 { get; set; }
        public int? Campaignrefs3 { get; set; }
        public int? Campaignrefs4 { get; set; }
        public int? Campaignrefs5 { get; set; }
        public int? Pointcampref { get; set; }
        public double? Camppoint { get; set; }
        public int? Promclasitemref { get; set; }
        public int? Cmpglineref { get; set; }
        public int? Plnsttranspernr { get; set; }
        public double? Pordclsplnamnt { get; set; }
        public double? Vendcomm { get; set; }
        public double? Previousoutcost { get; set; }
        public int? Costofsaleaccref { get; set; }
        public int? Purchaccref { get; set; }
        public int? Costofsalecntref { get; set; }
        public int? Purchcentref { get; set; }
        public double? Prevoutcostcurr { get; set; }
        public double? Abvatamount { get; set; }
        public int? Abvatstatus { get; set; }
        public double? Prrate { get; set; }
        public double? Addtaxrate { get; set; }
        public double? Addtaxconvfact { get; set; }
        public double? Addtaxamount { get; set; }
        public double? Addtaxprcost { get; set; }
        public double? Addtaxretcost { get; set; }
        public double? Addtaxretcostcurr { get; set; }
        public double? Grossuinfo1 { get; set; }
        public double? Grossuinfo2 { get; set; }
        public double? Addtaxprcostcurr { get; set; }
        public int? Addtaxaccref { get; set; }
        public int? Addtaxcenterref { get; set; }
        public short? Addtaxamntisupd { get; set; }
        public double? Infidx { get; set; }
        public int? Addtaxcosaccref { get; set; }
        public int? Addtaxcoscntref { get; set; }
        public double? Previousataxprcost { get; set; }
        public double? Prevataxprcostcurr { get; set; }
        public double? Prdordtotcoef { get; set; }
        public double? Dempeggedamnt { get; set; }
        public double? Stdunitcost { get; set; }
        public double? Stdrpunitcost { get; set; }
        public int? Costdiffaccref { get; set; }
        public int? Costdiffcenref { get; set; }
        public short? Textinc { get; set; }
        public double? Addtaxdiscamount { get; set; }
        public string Orglogoid { get; set; }
        public string Eximficheno { get; set; }
        public short? Eximfctype { get; set; }
        public short? Transexpline { get; set; }
        public short? Insexpline { get; set; }
        public int? Eximwhfcref { get; set; }
        public int? Eximwhlnref { get; set; }
        public int? Eximfileref { get; set; }
        public short? Eximprocnr { get; set; }
        public short? Eisrvdsttyp { get; set; }
        public int? Mainstlnref { get; set; }
        public short? Madeofshred { get; set; }
        public short? Fromordwithpay { get; set; }
        public int? Projectref { get; set; }
        public short? Status { get; set; }
        public short? Doreserve { get; set; }
        public int? Pointcamprefs1 { get; set; }
        public int? Pointcamprefs2 { get; set; }
        public int? Pointcamprefs3 { get; set; }
        public int? Pointcamprefs4 { get; set; }
        public double? Camppoints1 { get; set; }
        public double? Camppoints2 { get; set; }
        public double? Camppoints3 { get; set; }
        public double? Camppoints4 { get; set; }
        public int? Cmpglinerefs1 { get; set; }
        public int? Cmpglinerefs2 { get; set; }
        public int? Cmpglinerefs3 { get; set; }
        public int? Cmpglinerefs4 { get; set; }
        public int? Prclistref { get; set; }
        public short? Pordsymoutln { get; set; }
        public short? Month { get; set; }
        public short? Year { get; set; }
        public double? Exaddtaxrate { get; set; }
        public double? Exaddtaxconvf { get; set; }
        public int? Exaddtaxaref { get; set; }
        public int? Exaddtaxcref { get; set; }
        public int? Othraddtaxaref { get; set; }
        public int? Othraddtaxcref { get; set; }
        public double? Exaddtaxamnt { get; set; }
        public short? Affectcollatrl { get; set; }
        public short? Altpromflag { get; set; }
        public short? Eidistflnnr { get; set; }
        public short? Eximtype { get; set; }
        public int? Variantref { get; set; }
        public short? Candeduct { get; set; }
        public double? Outremamnt { get; set; }
        public double? Outremcost { get; set; }
        public double? Outremcostcurr { get; set; }
        public int? Reflvataccref { get; set; }
        public int? Reflvatothaccref { get; set; }
        public int? Parentlnref { get; set; }
        public short? Affectrisk { get; set; }
        public short? Ineffectivecost { get; set; }
        public double? Addtaxvatmatrah { get; set; }
        public int? Reflaccref { get; set; }
        public int? Reflothaccref { get; set; }
        public int? Camppaydefref { get; set; }
        public DateTime? Faregbinddate { get; set; }
        public int? Reltranslnref { get; set; }
        public short? Fromtransfer { get; set; }
        public double? Costdistprice { get; set; }
        public double? Costdistrepprice { get; set; }
        public double? Diffpriceufrs { get; set; }
        public double? Diffreppriceufrs { get; set; }
        public double? Outcostufrs { get; set; }
        public double? Outcostcurrufrs { get; set; }
        public double? Diffprcostufrs { get; set; }
        public double? Diffprcrcostufrs { get; set; }
        public double? Retcostufrs { get; set; }
        public double? Retcostcurrufrs { get; set; }
        public double? Outremcostufrs { get; set; }
        public double? Outremcostcurrufrs { get; set; }
        public double? Infidxufrs { get; set; }
        public double? Adjpriceufrs { get; set; }
        public double? Adjreppriceufrs { get; set; }
        public double? Adjprcostufrs { get; set; }
        public double? Adjprcrcostufrs { get; set; }
        public double? Costdistpriceufrs { get; set; }
        public double? Costdistreppriceufrs { get; set; }
        public int? Purchaccrefufrs { get; set; }
        public int? Purchcentrefufrs { get; set; }
        public int? Cosaccrefufrs { get; set; }
        public int? Coscntrefufrs { get; set; }
        public double? Proutcostufrsdiff { get; set; }
        public double? Proutcostcrufrsdiff { get; set; }
        public short? Underdeductlimit { get; set; }
        public string Globalid { get; set; }
        public short? Deductionpart1 { get; set; }
        public short? Deductionpart2 { get; set; }
        public string Guid { get; set; }
        public string Specode2 { get; set; }
        public int? Offerref { get; set; }
        public int? Offtransref { get; set; }
        public string Vatexceptreason { get; set; }
        public string Plndefserilotno { get; set; }
        public double? Plnunrsrvamount { get; set; }
        public double? Pordclsplnunrsrvamnt { get; set; }
        public short? Lprodrsrvstat { get; set; }
        public short? Falinktype { get; set; }
        public string Deductcode { get; set; }
        public short? Updthisline { get; set; }
        public string Vatexceptcode { get; set; }
        public string Porderficheno { get; set; }
        public int? Qprodfcref { get; set; }
        public int? Reltransfcref { get; set; }
        public string Ataxexceptreason { get; set; }
        public string Ataxexceptcode { get; set; }
        public short? Prodordertyp { get; set; }
        public int? Subcontorderref { get; set; }
        public short? Qprodfctyp { get; set; }
        public short? Prdordslplnreserve { get; set; }
        public DateTime? Infdate { get; set; }
        public short? Deststatus { get; set; }
        public int? Regtypref { get; set; }
        public int? Faprofitaccref { get; set; }
        public int? Faprofitcentref { get; set; }
        public int? Falossaccref { get; set; }
        public int? Falosscentref { get; set; }
        public string Cpacode { get; set; }
        public string Gtipcode { get; set; }
        public int? Publiccountryref { get; set; }
        public short? Qproditemtype { get; set; }
        public short? Futmonthcnt { get; set; }
        public int? Futmonthbegdate { get; set; }
        public int? Qctransferref { get; set; }
        public double? Qctransferamnt { get; set; }
        public DateTime? Futmonthenddate { get; set; }
        public int? Kkegaccref { get; set; }
        public int? Kkegcentref { get; set; }
        public int? Mntorderfref { get; set; }
        public double? Fakkegamount { get; set; }
        public short? Middlemanexptyp { get; set; }
        public int? Expraccref { get; set; }
        public int? Exprcntrref { get; set; }
        public int? Kkegvataccref { get; set; }
        public int? Kkegvatcentref { get; set; }
        public string Markingtagno { get; set; }
        public string Owner { get; set; }
        public string Tcktaxnr { get; set; }
        public DateTime? Futmonthbegdate1 { get; set; }
        public int? Addtaxvataccref { get; set; }
        public int? Addtaxvatcenref { get; set; }
        public short? Expdays { get; set; }
        public int? Cancelledinvref1 { get; set; }
        public int? Cancelledinvref2 { get; set; }
        public int? Cancelledinvref3 { get; set; }
        public int? Cancelledinvref4 { get; set; }
        public short? Fromintegtype { get; set; }
        public int? Fromintegref { get; set; }
    }
}
