using System;
using System.Collections.Generic;

#nullable disable

namespace Layer.Core.Models
{
    public partial class Lg00101Invoice
    {
        public int Logicalref { get; set; }
        public short? Grpcode { get; set; }
        public short? Trcode { get; set; }
        public string Ficheno { get; set; }
        public DateTime? Date { get; set; }
        public int? Time { get; set; }
        public string Docode { get; set; }
        public string Specode { get; set; }
        public string Cyphcode { get; set; }
        public int? Clientref { get; set; }
        public int? Recvref { get; set; }
        public int? Centerref { get; set; }
        public int? Accountref { get; set; }
        public short? Sourceindex { get; set; }
        public short? Sourcecostgrp { get; set; }
        public short? Cancelled { get; set; }
        public short? Accounted { get; set; }
        public short? Paidincash { get; set; }
        public short? Fromkasa { get; set; }
        public short? Entegset { get; set; }
        public double? Vat { get; set; }
        public double? Adddiscounts { get; set; }
        public double? Totaldiscounts { get; set; }
        public double? Totaldiscounted { get; set; }
        public double? Addexpenses { get; set; }
        public double? Totalexpenses { get; set; }
        public double? Distexpense { get; set; }
        public double? Totaldepozito { get; set; }
        public double? Totalpromotions { get; set; }
        public double? Vatincgross { get; set; }
        public double? Totalvat { get; set; }
        public double? Grosstotal { get; set; }
        public double? Nettotal { get; set; }
        public string Genexp1 { get; set; }
        public string Genexp2 { get; set; }
        public string Genexp3 { get; set; }
        public string Genexp4 { get; set; }
        public string Genexp5 { get; set; }
        public string Genexp6 { get; set; }
        public double? Interestapp { get; set; }
        public short? Trcurr { get; set; }
        public double? Trrate { get; set; }
        public double? Trnet { get; set; }
        public double? Reportrate { get; set; }
        public double? Reportnet { get; set; }
        public short? Onlyonepayline { get; set; }
        public int? Kastransref { get; set; }
        public int? Paydefref { get; set; }
        public short? Printcnt { get; set; }
        public short? Gvatinc { get; set; }
        public short? Branch { get; set; }
        public short? Department { get; set; }
        public int? Accficheref { get; set; }
        public int? Addexpaccref { get; set; }
        public int? Addexpcentref { get; set; }
        public short? Decprdiff { get; set; }
        public short? CapiblockCreatedby { get; set; }
        public DateTime? CapiblockCreadeddate { get; set; }
        public short? CapiblockCreatedhour { get; set; }
        public short? CapiblockCreatedmin { get; set; }
        public short? CapiblockCreatedsec { get; set; }
        public short? CapiblockModifiedby { get; set; }
        public DateTime? CapiblockModifieddate { get; set; }
        public short? CapiblockModifiedhour { get; set; }
        public short? CapiblockModifiedmin { get; set; }
        public short? CapiblockModifiedsec { get; set; }
        public int? Salesmanref { get; set; }
        public short? Cancelledacc { get; set; }
        public string Shptypcod { get; set; }
        public string Shpagncod { get; set; }
        public string Tracknr { get; set; }
        public short? Genexctyp { get; set; }
        public short? Lineexctyp { get; set; }
        public string Tradinggrp { get; set; }
        public short? Textinc { get; set; }
        public short? Siteid { get; set; }
        public short? Recstatus { get; set; }
        public int? Orglogicref { get; set; }
        public short? Factorynr { get; set; }
        public int? Wfstatus { get; set; }
        public int? Shipinforef { get; set; }
        public int? Distorderref { get; set; }
        public short? Sendcnt { get; set; }
        public short? Dlvclient { get; set; }
        public int? Costofsalefcref { get; set; }
        public short? Opstat { get; set; }
        public string Doctrackingnr { get; set; }
        public double? Totaladdtax { get; set; }
        public short? Paymenttype { get; set; }
        public double? Infidx { get; set; }
        public short? Accountedcnt { get; set; }
        public string Orglogoid { get; set; }
        public short? Fromexim { get; set; }
        public string Frgtypcod { get; set; }
        public short? Eximfctype { get; set; }
        public short? Fromordwithpay { get; set; }
        public int? Projectref { get; set; }
        public int? Wflowcrdref { get; set; }
        public short? Status { get; set; }
        public short? Deductionpart1 { get; set; }
        public short? Deductionpart2 { get; set; }
        public double? Totalexaddtax { get; set; }
        public short? Exaccounted { get; set; }
        public short? Frombank { get; set; }
        public int? Bntransref { get; set; }
        public short? Affectcollatrl { get; set; }
        public short? Grpfirmtrans { get; set; }
        public short? Affectrisk { get; set; }
        public short? Controlinfo { get; set; }
        public short? Postransferinfo { get; set; }
        public short? Taxfreechx { get; set; }
        public string Passportno { get; set; }
        public string Creditcardno { get; set; }
        public short? Ineffectivecost { get; set; }
        public short? Reflected { get; set; }
        public int? Reflaccficheref { get; set; }
        public short? Cancelledreflacc { get; set; }
        public string Creditcardnum { get; set; }
        public short? Approve { get; set; }
        public DateTime? Approvedate { get; set; }
        public short? Cantcrededuct { get; set; }
        public short? Entrust { get; set; }
        public DateTime? Docdate { get; set; }
        public short? Einvoice { get; set; }
        public short? Profileid { get; set; }
        public string Guid { get; set; }
        public short? Estatus { get; set; }
        public DateTime? Estartdate { get; set; }
        public DateTime? Eenddate { get; set; }
        public string Edescription { get; set; }
        public double? Eduration { get; set; }
        public short? Edurationtype { get; set; }
        public short? Devir { get; set; }
        public double? Distadjpriceufrs { get; set; }
        public int? Cosfcrefufrs { get; set; }
        public string Globalid { get; set; }
        public double? Totalservices { get; set; }
        public short? Fromleasing { get; set; }
        public string Cancelexp { get; set; }
        public string Undoexp { get; set; }
        public string Vatexceptreason { get; set; }
        public string Campaigncode { get; set; }
        public short? Canceldespsinv { get; set; }
        public short? Fromexchdiff { get; set; }
        public short? Eximvat { get; set; }
        public string Serialcode { get; set; }
        public short? Appcldeductlim { get; set; }
        public short? Einvoicetyp { get; set; }
        public string Vatexceptcode { get; set; }
        public int? Offerref { get; set; }
        public string Ataxexceptreason { get; set; }
        public string Ataxexceptcode { get; set; }
        public short? Fromstaffotherex { get; set; }
        public short? Nocalculate { get; set; }
        public short? Insteadofdesp { get; set; }
        public short? Okcfiche { get; set; }
        public DateTime? Canceldate { get; set; }
        public string Frgtypdesc { get; set; }
        public int? Markref { get; set; }
        public DateTime? Printdate { get; set; }
        public string Delivercode { get; set; }
        public short? Accepteinvpublic { get; set; }
        public int? Publicbnaccref { get; set; }
        public string Typecode { get; set; }
        public short? Futmnthyrexpinc { get; set; }
        public short? Docdetail { get; set; }
        public short? Calcaddtaxvatsep { get; set; }
        public DateTime? Esenddate { get; set; }
        public short? Electdoc { get; set; }
        public int? Notifycrdref { get; set; }
        public int? Gibaccficheref { get; set; }
        public short? Fromintegtype { get; set; }
    }
}
