using System;
using System.Collections.Generic;

#nullable disable

namespace Layer.Core.Models
{
    public partial class Lg001Prcard
    {
        public int Logicalref { get; set; }
        public string Code { get; set; }
        public string Definition { get; set; }
        public string Specode { get; set; }
        public string Cyphcode { get; set; }
        public short? Cardtype { get; set; }
        public int? Stockref { get; set; }
        public short? Mtrltype { get; set; }
        public DateTime? Begdate { get; set; }
        public DateTime? Enddate { get; set; }
        public int? Counter { get; set; }
        public double? Price { get; set; }
        public int? Promlines1Stockref { get; set; }
        public string Promlines1Formula { get; set; }
        public double? Promlines1Price { get; set; }
        public double? Promlines1Rndval { get; set; }
        public int? Promlines1Uomref { get; set; }
        public short? Promlines1Siteid { get; set; }
        public short? Promlines1Recstatus { get; set; }
        public int? Promlines1Orglogicref { get; set; }
        public int? Promlines1Wfstatus { get; set; }
        public int? Promlines1Variantref { get; set; }
        public int? Promlines2Stockref { get; set; }
        public string Promlines2Formula { get; set; }
        public double? Promlines2Price { get; set; }
        public double? Promlines2Rndval { get; set; }
        public int? Promlines2Uomref { get; set; }
        public short? Promlines2Siteid { get; set; }
        public short? Promlines2Recstatus { get; set; }
        public int? Promlines2Orglogicref { get; set; }
        public int? Promlines2Wfstatus { get; set; }
        public int? Promlines2Variantref { get; set; }
        public int? Promlines3Stockref { get; set; }
        public string Promlines3Formula { get; set; }
        public double? Promlines3Price { get; set; }
        public double? Promlines3Rndval { get; set; }
        public int? Promlines3Uomref { get; set; }
        public short? Promlines3Siteid { get; set; }
        public short? Promlines3Recstatus { get; set; }
        public int? Promlines3Orglogicref { get; set; }
        public int? Promlines3Wfstatus { get; set; }
        public int? Promlines3Variantref { get; set; }
        public int? Promlines4Stockref { get; set; }
        public string Promlines4Formula { get; set; }
        public double? Promlines4Price { get; set; }
        public double? Promlines4Rndval { get; set; }
        public int? Promlines4Uomref { get; set; }
        public short? Promlines4Siteid { get; set; }
        public short? Promlines4Recstatus { get; set; }
        public int? Promlines4Orglogicref { get; set; }
        public int? Promlines4Wfstatus { get; set; }
        public int? Promlines4Variantref { get; set; }
        public int? Promlines5Stockref { get; set; }
        public string Promlines5Formula { get; set; }
        public double? Promlines5Price { get; set; }
        public double? Promlines5Rndval { get; set; }
        public int? Promlines5Uomref { get; set; }
        public short? Promlines5Siteid { get; set; }
        public short? Promlines5Recstatus { get; set; }
        public int? Promlines5Orglogicref { get; set; }
        public int? Promlines5Wfstatus { get; set; }
        public int? Promlines5Variantref { get; set; }
        public int? Promlines6Stockref { get; set; }
        public string Promlines6Formula { get; set; }
        public double? Promlines6Price { get; set; }
        public double? Promlines6Rndval { get; set; }
        public int? Promlines6Uomref { get; set; }
        public short? Promlines6Siteid { get; set; }
        public short? Promlines6Recstatus { get; set; }
        public int? Promlines6Orglogicref { get; set; }
        public int? Promlines6Wfstatus { get; set; }
        public int? Promlines6Variantref { get; set; }
        public int? Promlines7Stockref { get; set; }
        public string Promlines7Formula { get; set; }
        public double? Promlines7Price { get; set; }
        public double? Promlines7Rndval { get; set; }
        public int? Promlines7Uomref { get; set; }
        public short? Promlines7Siteid { get; set; }
        public short? Promlines7Recstatus { get; set; }
        public int? Promlines7Orglogicref { get; set; }
        public int? Promlines7Wfstatus { get; set; }
        public int? Promlines7Variantref { get; set; }
        public int? Promlines8Stockref { get; set; }
        public string Promlines8Formula { get; set; }
        public double? Promlines8Price { get; set; }
        public double? Promlines8Rndval { get; set; }
        public int? Promlines8Uomref { get; set; }
        public short? Promlines8Siteid { get; set; }
        public short? Promlines8Recstatus { get; set; }
        public int? Promlines8Orglogicref { get; set; }
        public int? Promlines8Wfstatus { get; set; }
        public int? Promlines8Variantref { get; set; }
        public int? Promlines9Stockref { get; set; }
        public string Promlines9Formula { get; set; }
        public double? Promlines9Price { get; set; }
        public double? Promlines9Rndval { get; set; }
        public int? Promlines9Uomref { get; set; }
        public short? Promlines9Siteid { get; set; }
        public short? Promlines9Recstatus { get; set; }
        public int? Promlines9Orglogicref { get; set; }
        public int? Promlines9Wfstatus { get; set; }
        public int? Promlines9Variantref { get; set; }
        public int? Promlines10Stockref { get; set; }
        public string Promlines10Formula { get; set; }
        public double? Promlines10Price { get; set; }
        public double? Promlines10Rndval { get; set; }
        public int? Promlines10Uomref { get; set; }
        public short? Promlines10Siteid { get; set; }
        public short? Promlines10Recstatus { get; set; }
        public int? Promlines10Orglogicref { get; set; }
        public int? Promlines10Wfstatus { get; set; }
        public int? Promlines10Variantref { get; set; }
        public int? Promlines11Stockref { get; set; }
        public string Promlines11Formula { get; set; }
        public double? Promlines11Price { get; set; }
        public double? Promlines11Rndval { get; set; }
        public int? Promlines11Uomref { get; set; }
        public short? Promlines11Siteid { get; set; }
        public short? Promlines11Recstatus { get; set; }
        public int? Promlines11Orglogicref { get; set; }
        public int? Promlines11Wfstatus { get; set; }
        public int? Promlines11Variantref { get; set; }
        public int? Promlines12Stockref { get; set; }
        public string Promlines12Formula { get; set; }
        public double? Promlines12Price { get; set; }
        public double? Promlines12Rndval { get; set; }
        public int? Promlines12Uomref { get; set; }
        public short? Promlines12Siteid { get; set; }
        public short? Promlines12Recstatus { get; set; }
        public int? Promlines12Orglogicref { get; set; }
        public int? Promlines12Wfstatus { get; set; }
        public int? Promlines12Variantref { get; set; }
        public int? Promlines13Stockref { get; set; }
        public string Promlines13Formula { get; set; }
        public double? Promlines13Price { get; set; }
        public double? Promlines13Rndval { get; set; }
        public int? Promlines13Uomref { get; set; }
        public short? Promlines13Siteid { get; set; }
        public short? Promlines13Recstatus { get; set; }
        public int? Promlines13Orglogicref { get; set; }
        public int? Promlines13Wfstatus { get; set; }
        public int? Promlines13Variantref { get; set; }
        public int? Promlines14Stockref { get; set; }
        public string Promlines14Formula { get; set; }
        public double? Promlines14Price { get; set; }
        public double? Promlines14Rndval { get; set; }
        public int? Promlines14Uomref { get; set; }
        public short? Promlines14Siteid { get; set; }
        public short? Promlines14Recstatus { get; set; }
        public int? Promlines14Orglogicref { get; set; }
        public int? Promlines14Wfstatus { get; set; }
        public int? Promlines14Variantref { get; set; }
        public int? Promlines15Stockref { get; set; }
        public string Promlines15Formula { get; set; }
        public double? Promlines15Price { get; set; }
        public double? Promlines15Rndval { get; set; }
        public int? Promlines15Uomref { get; set; }
        public short? Promlines15Siteid { get; set; }
        public short? Promlines15Recstatus { get; set; }
        public int? Promlines15Orglogicref { get; set; }
        public int? Promlines15Wfstatus { get; set; }
        public int? Promlines15Variantref { get; set; }
        public int? Promlines16Stockref { get; set; }
        public string Promlines16Formula { get; set; }
        public double? Promlines16Price { get; set; }
        public double? Promlines16Rndval { get; set; }
        public int? Promlines16Uomref { get; set; }
        public short? Promlines16Siteid { get; set; }
        public short? Promlines16Recstatus { get; set; }
        public int? Promlines16Orglogicref { get; set; }
        public int? Promlines16Wfstatus { get; set; }
        public int? Promlines16Variantref { get; set; }
        public int? Promlines17Stockref { get; set; }
        public string Promlines17Formula { get; set; }
        public double? Promlines17Price { get; set; }
        public double? Promlines17Rndval { get; set; }
        public int? Promlines17Uomref { get; set; }
        public short? Promlines17Siteid { get; set; }
        public short? Promlines17Recstatus { get; set; }
        public int? Promlines17Orglogicref { get; set; }
        public int? Promlines17Wfstatus { get; set; }
        public int? Promlines17Variantref { get; set; }
        public int? Promlines18Stockref { get; set; }
        public string Promlines18Formula { get; set; }
        public double? Promlines18Price { get; set; }
        public double? Promlines18Rndval { get; set; }
        public int? Promlines18Uomref { get; set; }
        public short? Promlines18Siteid { get; set; }
        public short? Promlines18Recstatus { get; set; }
        public int? Promlines18Orglogicref { get; set; }
        public int? Promlines18Wfstatus { get; set; }
        public int? Promlines18Variantref { get; set; }
        public int? Promlines19Stockref { get; set; }
        public string Promlines19Formula { get; set; }
        public double? Promlines19Price { get; set; }
        public double? Promlines19Rndval { get; set; }
        public int? Promlines19Uomref { get; set; }
        public short? Promlines19Siteid { get; set; }
        public short? Promlines19Recstatus { get; set; }
        public int? Promlines19Orglogicref { get; set; }
        public int? Promlines19Wfstatus { get; set; }
        public int? Promlines19Variantref { get; set; }
        public int? Promlines20Stockref { get; set; }
        public string Promlines20Formula { get; set; }
        public double? Promlines20Price { get; set; }
        public double? Promlines20Rndval { get; set; }
        public int? Promlines20Uomref { get; set; }
        public short? Promlines20Siteid { get; set; }
        public short? Promlines20Recstatus { get; set; }
        public int? Promlines20Orglogicref { get; set; }
        public int? Promlines20Wfstatus { get; set; }
        public int? Promlines20Variantref { get; set; }
        public int? Promlines21Stockref { get; set; }
        public string Promlines21Formula { get; set; }
        public double? Promlines21Price { get; set; }
        public double? Promlines21Rndval { get; set; }
        public int? Promlines21Uomref { get; set; }
        public short? Promlines21Siteid { get; set; }
        public short? Promlines21Recstatus { get; set; }
        public int? Promlines21Orglogicref { get; set; }
        public int? Promlines21Wfstatus { get; set; }
        public int? Promlines21Variantref { get; set; }
        public int? Promlines22Stockref { get; set; }
        public string Promlines22Formula { get; set; }
        public double? Promlines22Price { get; set; }
        public double? Promlines22Rndval { get; set; }
        public int? Promlines22Uomref { get; set; }
        public short? Promlines22Siteid { get; set; }
        public short? Promlines22Recstatus { get; set; }
        public int? Promlines22Orglogicref { get; set; }
        public int? Promlines22Wfstatus { get; set; }
        public int? Promlines22Variantref { get; set; }
        public int? Promlines23Stockref { get; set; }
        public string Promlines23Formula { get; set; }
        public double? Promlines23Price { get; set; }
        public double? Promlines23Rndval { get; set; }
        public int? Promlines23Uomref { get; set; }
        public short? Promlines23Siteid { get; set; }
        public short? Promlines23Recstatus { get; set; }
        public int? Promlines23Orglogicref { get; set; }
        public int? Promlines23Wfstatus { get; set; }
        public int? Promlines23Variantref { get; set; }
        public int? Promlines24Stockref { get; set; }
        public string Promlines24Formula { get; set; }
        public double? Promlines24Price { get; set; }
        public double? Promlines24Rndval { get; set; }
        public int? Promlines24Uomref { get; set; }
        public short? Promlines24Siteid { get; set; }
        public short? Promlines24Recstatus { get; set; }
        public int? Promlines24Orglogicref { get; set; }
        public int? Promlines24Wfstatus { get; set; }
        public int? Promlines24Variantref { get; set; }
        public int? Promlines25Stockref { get; set; }
        public string Promlines25Formula { get; set; }
        public double? Promlines25Price { get; set; }
        public double? Promlines25Rndval { get; set; }
        public int? Promlines25Uomref { get; set; }
        public short? Promlines25Siteid { get; set; }
        public short? Promlines25Recstatus { get; set; }
        public int? Promlines25Orglogicref { get; set; }
        public int? Promlines25Wfstatus { get; set; }
        public int? Promlines25Variantref { get; set; }
        public int? Promlines26Stockref { get; set; }
        public string Promlines26Formula { get; set; }
        public double? Promlines26Price { get; set; }
        public double? Promlines26Rndval { get; set; }
        public int? Promlines26Uomref { get; set; }
        public short? Promlines26Siteid { get; set; }
        public short? Promlines26Recstatus { get; set; }
        public int? Promlines26Orglogicref { get; set; }
        public int? Promlines26Wfstatus { get; set; }
        public int? Promlines26Variantref { get; set; }
        public int? Promlines27Stockref { get; set; }
        public string Promlines27Formula { get; set; }
        public double? Promlines27Price { get; set; }
        public double? Promlines27Rndval { get; set; }
        public int? Promlines27Uomref { get; set; }
        public short? Promlines27Siteid { get; set; }
        public short? Promlines27Recstatus { get; set; }
        public int? Promlines27Orglogicref { get; set; }
        public int? Promlines27Wfstatus { get; set; }
        public int? Promlines27Variantref { get; set; }
        public int? Promlines28Stockref { get; set; }
        public string Promlines28Formula { get; set; }
        public double? Promlines28Price { get; set; }
        public double? Promlines28Rndval { get; set; }
        public int? Promlines28Uomref { get; set; }
        public short? Promlines28Siteid { get; set; }
        public short? Promlines28Recstatus { get; set; }
        public int? Promlines28Orglogicref { get; set; }
        public int? Promlines28Wfstatus { get; set; }
        public int? Promlines28Variantref { get; set; }
        public int? Promlines29Stockref { get; set; }
        public string Promlines29Formula { get; set; }
        public double? Promlines29Price { get; set; }
        public double? Promlines29Rndval { get; set; }
        public int? Promlines29Uomref { get; set; }
        public short? Promlines29Siteid { get; set; }
        public short? Promlines29Recstatus { get; set; }
        public int? Promlines29Orglogicref { get; set; }
        public int? Promlines29Wfstatus { get; set; }
        public int? Promlines29Variantref { get; set; }
        public int? Promlines30Stockref { get; set; }
        public string Promlines30Formula { get; set; }
        public double? Promlines30Price { get; set; }
        public double? Promlines30Rndval { get; set; }
        public int? Promlines30Uomref { get; set; }
        public short? Promlines30Siteid { get; set; }
        public short? Promlines30Recstatus { get; set; }
        public int? Promlines30Orglogicref { get; set; }
        public int? Promlines30Wfstatus { get; set; }
        public int? Promlines30Variantref { get; set; }
        public short? CapiblockCreatedby { get; set; }
        public DateTime? CapiblockCreadeddate { get; set; }
        public short? CapiblockCreatedhour { get; set; }
        public short? CapiblockCreatedmin { get; set; }
        public short? CapiblockCreatedsec { get; set; }
        public short? CapiblockModifiedby { get; set; }
        public DateTime? CapiblockModifieddate { get; set; }
        public short? CapiblockModifiedhour { get; set; }
        public short? CapiblockModifiedmin { get; set; }
        public short? CapiblockModifiedsec { get; set; }
        public short? Fichemodul { get; set; }
        public short? Fichetypes1 { get; set; }
        public short? Fichetypes2 { get; set; }
        public short? Fichetypes3 { get; set; }
        public short? Active { get; set; }
        public short? Siteid { get; set; }
        public short? Recstatus { get; set; }
        public int? Orglogicref { get; set; }
        public int? Wfstatus { get; set; }
        public short? Ordfcmodul { get; set; }
        public int? Variantref { get; set; }
    }
}
