using System;
using System.Collections.Generic;

#nullable disable

namespace Layer.Core.Models
{
    public partial class Lg00101Stfiche
    {
        public int Logicalref { get; set; }
        public short? Grpcode { get; set; }
        public short? Trcode { get; set; }
        public short? Iocode { get; set; }
        public string Ficheno { get; set; }
        public DateTime? Date { get; set; }
        public int? Ftime { get; set; }
        public string Docode { get; set; }
        public string Invno { get; set; }
        public string Specode { get; set; }
        public string Cyphcode { get; set; }
        public int? Invoiceref { get; set; }
        public int? Clientref { get; set; }
        public int? Recvref { get; set; }
        public int? Accountref { get; set; }
        public int? Centerref { get; set; }
        public int? Prodorderref { get; set; }
        public string Porderficheno { get; set; }
        public short? Sourcetype { get; set; }
        public short? Sourceindex { get; set; }
        public int? Sourcewsref { get; set; }
        public int? Sourcepolnref { get; set; }
        public short? Sourcecostgrp { get; set; }
        public short? Desttype { get; set; }
        public short? Destindex { get; set; }
        public int? Destwsref { get; set; }
        public int? Destpolnref { get; set; }
        public short? Destcostgrp { get; set; }
        public short? Factorynr { get; set; }
        public short? Branch { get; set; }
        public short? Department { get; set; }
        public short? Compbranch { get; set; }
        public short? Compdepartment { get; set; }
        public short? Compfactory { get; set; }
        public short? Prodstat { get; set; }
        public short? Devir { get; set; }
        public short? Cancelled { get; set; }
        public short? Billed { get; set; }
        public short? Accounted { get; set; }
        public short? Updcurr { get; set; }
        public short? Inuse { get; set; }
        public short? Invkind { get; set; }
        public double? Adddiscounts { get; set; }
        public double? Totaldiscounts { get; set; }
        public double? Totaldiscounted { get; set; }
        public double? Addexpenses { get; set; }
        public double? Totalexpenses { get; set; }
        public double? Totaldepozito { get; set; }
        public double? Totalpromotions { get; set; }
        public double? Totalvat { get; set; }
        public double? Grosstotal { get; set; }
        public double? Nettotal { get; set; }
        public string Genexp1 { get; set; }
        public string Genexp2 { get; set; }
        public string Genexp3 { get; set; }
        public string Genexp4 { get; set; }
        public string Genexp5 { get; set; }
        public string Genexp6 { get; set; }
        public double? Reportrate { get; set; }
        public double? Reportnet { get; set; }
        public int? Extenref { get; set; }
        public int? Paydefref { get; set; }
        public short? Printcnt { get; set; }
        public short? Fichecnt { get; set; }
        public int? Accficheref { get; set; }
        public short? CapiblockCreatedby { get; set; }
        public DateTime? CapiblockCreadeddate { get; set; }
        public short? CapiblockCreatedhour { get; set; }
        public short? CapiblockCreatedmin { get; set; }
        public short? CapiblockCreatedsec { get; set; }
        public short? CapiblockModifiedby { get; set; }
        public DateTime? CapiblockModifieddate { get; set; }
        public short? CapiblockModifiedhour { get; set; }
        public short? CapiblockModifiedmin { get; set; }
        public short? CapiblockModifiedsec { get; set; }
        public int? Salesmanref { get; set; }
        public short? Cancelledacc { get; set; }
        public string Shptypcod { get; set; }
        public string Shpagncod { get; set; }
        public string Tracknr { get; set; }
        public short? Genexctyp { get; set; }
        public short? Lineexctyp { get; set; }
        public string Tradinggrp { get; set; }
        public short? Textinc { get; set; }
        public short? Siteid { get; set; }
        public short? Recstatus { get; set; }
        public int? Orglogicref { get; set; }
        public int? Wfstatus { get; set; }
        public int? Shipinforef { get; set; }
        public int? Distorderref { get; set; }
        public short? Sendcnt { get; set; }
        public short? Dlvclient { get; set; }
        public string Doctrackingnr { get; set; }
        public short? Addtaxcalc { get; set; }
        public double? Totaladdtax { get; set; }
        public string Ugirtrackingno { get; set; }
        public int? Qprodfcref { get; set; }
        public int? Vaaccref { get; set; }
        public int? Vacenterref { get; set; }
        public string Orglogoid { get; set; }
        public short? Fromexim { get; set; }
        public string Frgtypcod { get; set; }
        public short? Trcurr { get; set; }
        public double? Trrate { get; set; }
        public double? Trnet { get; set; }
        public int? Eximwhfcref { get; set; }
        public short? Eximfctype { get; set; }
        public int? Mainstfcref { get; set; }
        public short? Fromordwithpay { get; set; }
        public int? Projectref { get; set; }
        public int? Wflowcrdref { get; set; }
        public short? Status { get; set; }
        public short? Updtrcurr { get; set; }
        public double? Totalexaddtax { get; set; }
        public short? Affectcollatrl { get; set; }
        public short? Deductionpart1 { get; set; }
        public short? Deductionpart2 { get; set; }
        public short? Grpfirmtrans { get; set; }
        public short? Affectrisk { get; set; }
        public short? Dispstatus { get; set; }
        public short? Approve { get; set; }
        public DateTime? Approvedate { get; set; }
        public short? Cantcrededuct { get; set; }
        public DateTime? Shipdate { get; set; }
        public int? Shiptime { get; set; }
        public short? Entrustdevir { get; set; }
        public int? Reltransfcref { get; set; }
        public short? Fromtransfer { get; set; }
        public string Guid { get; set; }
        public string Globalid { get; set; }
        public int? Compstfcref { get; set; }
        public int? Compinvref { get; set; }
        public double? Totalservices { get; set; }
        public string Campaigncode { get; set; }
        public int? Offerref { get; set; }
        public short? Einvoicetyp { get; set; }
        public short? Einvoice { get; set; }
        public short? Nocalculate { get; set; }
        public short? Prodordertyp { get; set; }
        public short? Qprodfctyp { get; set; }
        public DateTime? Printdate { get; set; }
        public short? Prdordslplnreserve { get; set; }
        public short? Controlinfo { get; set; }
        public short? Edespatch { get; set; }
        public DateTime? Docdate { get; set; }
        public int? Doctime { get; set; }
        public short? Edespstatus { get; set; }
        public short? Profileid { get; set; }
        public string Deliverycode { get; set; }
        public short? Deststatus { get; set; }
        public string Cancelexp { get; set; }
        public string Undoexp { get; set; }
        public DateTime? Canceldate { get; set; }
        public short? Createwhere { get; set; }
        public int? Publicbnaccref { get; set; }
        public short? Accepteinvpublic { get; set; }
        public string Vatexceptcode { get; set; }
        public string Vatexceptreason { get; set; }
        public string Ataxexceptcode { get; set; }
        public string Ataxexceptreason { get; set; }
        public short? Taxfreechx { get; set; }
        public int? Mntorderfref { get; set; }
        public string Printeddespfcno { get; set; }
        public short? Okcfiche { get; set; }
        public DateTime? Esenddate { get; set; }
        public int? Notifycrdref { get; set; }
        public int? Cancelledinvref1 { get; set; }
        public int? Cancelledinvref2 { get; set; }
        public int? Cancelledinvref3 { get; set; }
        public int? Cancelledinvref4 { get; set; }
        public short? Fromintegtype { get; set; }
        public int? Fromintegref { get; set; }
    }
}
