using System;
using System.Collections.Generic;

#nullable disable

namespace Layer.Core.Models
{
    public partial class Lg001Taxdeclline
    {
        public int Logicalref { get; set; }
        public int? Taxdeclref { get; set; }
        public short? Listtyp { get; set; }
        public int? Linenr { get; set; }
        public string Txtarr1 { get; set; }
        public string Txtarr2 { get; set; }
        public string Txtarr3 { get; set; }
        public string Txtarr4 { get; set; }
        public string Txtarr5 { get; set; }
        public string Txtarr6 { get; set; }
        public string Txtarr7 { get; set; }
        public string Txtarr8 { get; set; }
        public string Txtarr9 { get; set; }
        public string Txtarr10 { get; set; }
        public string Txtarr11 { get; set; }
        public string Txtarr12 { get; set; }
        public string Txtarr13 { get; set; }
        public string Txtarr14 { get; set; }
        public string Txtarr15 { get; set; }
        public string Txtarr16 { get; set; }
        public string Txtarr17 { get; set; }
        public string Txtarr18 { get; set; }
        public string Txtarr19 { get; set; }
        public string Txtarr20 { get; set; }
        public string Txtarr21 { get; set; }
        public string Txtarr22 { get; set; }
        public string Txtarr23 { get; set; }
        public string Txtarr24 { get; set; }
        public string Txtarr25 { get; set; }
        public DateTime? Dtarr1 { get; set; }
        public DateTime? Dtarr2 { get; set; }
        public DateTime? Dtarr3 { get; set; }
        public double? Numarr1 { get; set; }
        public double? Numarr2 { get; set; }
        public double? Numarr3 { get; set; }
        public double? Numarr4 { get; set; }
        public double? Numarr5 { get; set; }
        public double? Numarr6 { get; set; }
        public double? Numarr7 { get; set; }
        public double? Numarr8 { get; set; }
        public double? Numarr9 { get; set; }
        public double? Numarr10 { get; set; }
        public double? Numarr11 { get; set; }
        public double? Numarr12 { get; set; }
        public double? Numarr13 { get; set; }
        public double? Numarr14 { get; set; }
        public double? Numarr15 { get; set; }
        public short? Intarr1 { get; set; }
        public short? Intarr2 { get; set; }
        public short? Intarr3 { get; set; }
        public short? Intarr4 { get; set; }
        public short? Intarr5 { get; set; }
        public short? Intarr6 { get; set; }
        public short? Intarr7 { get; set; }
        public short? Accarr1Itemlevel { get; set; }
        public short? Accarr1Itemtype { get; set; }
        public string Accarr1Itemcode { get; set; }
        public string Accarr1Itemname { get; set; }
        public string Accarr1Begcode { get; set; }
        public string Accarr1Endcode { get; set; }
        public short? Accarr1Acctype { get; set; }
        public short? Accarr1Remtype { get; set; }
        public short? Accarr1Tottype { get; set; }
        public string Accarr1Formula { get; set; }
        public double? Accarr1Total { get; set; }
        public short? Accarr2Itemlevel { get; set; }
        public short? Accarr2Itemtype { get; set; }
        public string Accarr2Itemcode { get; set; }
        public string Accarr2Itemname { get; set; }
        public string Accarr2Begcode { get; set; }
        public string Accarr2Endcode { get; set; }
        public short? Accarr2Acctype { get; set; }
        public short? Accarr2Remtype { get; set; }
        public short? Accarr2Tottype { get; set; }
        public string Accarr2Formula { get; set; }
        public double? Accarr2Total { get; set; }
        public short? Accarr3Itemlevel { get; set; }
        public short? Accarr3Itemtype { get; set; }
        public string Accarr3Itemcode { get; set; }
        public string Accarr3Itemname { get; set; }
        public string Accarr3Begcode { get; set; }
        public string Accarr3Endcode { get; set; }
        public short? Accarr3Acctype { get; set; }
        public short? Accarr3Remtype { get; set; }
        public short? Accarr3Tottype { get; set; }
        public string Accarr3Formula { get; set; }
        public double? Accarr3Total { get; set; }
        public short? Accarr4Itemlevel { get; set; }
        public short? Accarr4Itemtype { get; set; }
        public string Accarr4Itemcode { get; set; }
        public string Accarr4Itemname { get; set; }
        public string Accarr4Begcode { get; set; }
        public string Accarr4Endcode { get; set; }
        public short? Accarr4Acctype { get; set; }
        public short? Accarr4Remtype { get; set; }
        public short? Accarr4Tottype { get; set; }
        public string Accarr4Formula { get; set; }
        public double? Accarr4Total { get; set; }
        public short? Accarr5Itemlevel { get; set; }
        public short? Accarr5Itemtype { get; set; }
        public string Accarr5Itemcode { get; set; }
        public string Accarr5Itemname { get; set; }
        public string Accarr5Begcode { get; set; }
        public string Accarr5Endcode { get; set; }
        public short? Accarr5Acctype { get; set; }
        public short? Accarr5Remtype { get; set; }
        public short? Accarr5Tottype { get; set; }
        public string Accarr5Formula { get; set; }
        public double? Accarr5Total { get; set; }
        public short? Accarr6Itemlevel { get; set; }
        public short? Accarr6Itemtype { get; set; }
        public string Accarr6Itemcode { get; set; }
        public string Accarr6Itemname { get; set; }
        public string Accarr6Begcode { get; set; }
        public string Accarr6Endcode { get; set; }
        public short? Accarr6Acctype { get; set; }
        public short? Accarr6Remtype { get; set; }
        public short? Accarr6Tottype { get; set; }
        public string Accarr6Formula { get; set; }
        public double? Accarr6Total { get; set; }
        public short? Accarr7Itemlevel { get; set; }
        public short? Accarr7Itemtype { get; set; }
        public string Accarr7Itemcode { get; set; }
        public string Accarr7Itemname { get; set; }
        public string Accarr7Begcode { get; set; }
        public string Accarr7Endcode { get; set; }
        public short? Accarr7Acctype { get; set; }
        public short? Accarr7Remtype { get; set; }
        public short? Accarr7Tottype { get; set; }
        public string Accarr7Formula { get; set; }
        public double? Accarr7Total { get; set; }
        public short? Accarr8Itemlevel { get; set; }
        public short? Accarr8Itemtype { get; set; }
        public string Accarr8Itemcode { get; set; }
        public string Accarr8Itemname { get; set; }
        public string Accarr8Begcode { get; set; }
        public string Accarr8Endcode { get; set; }
        public short? Accarr8Acctype { get; set; }
        public short? Accarr8Remtype { get; set; }
        public short? Accarr8Tottype { get; set; }
        public string Accarr8Formula { get; set; }
        public double? Accarr8Total { get; set; }
        public short? Accarr9Itemlevel { get; set; }
        public short? Accarr9Itemtype { get; set; }
        public string Accarr9Itemcode { get; set; }
        public string Accarr9Itemname { get; set; }
        public string Accarr9Begcode { get; set; }
        public string Accarr9Endcode { get; set; }
        public short? Accarr9Acctype { get; set; }
        public short? Accarr9Remtype { get; set; }
        public short? Accarr9Tottype { get; set; }
        public string Accarr9Formula { get; set; }
        public double? Accarr9Total { get; set; }
        public short? Accarr10Itemlevel { get; set; }
        public short? Accarr10Itemtype { get; set; }
        public string Accarr10Itemcode { get; set; }
        public string Accarr10Itemname { get; set; }
        public string Accarr10Begcode { get; set; }
        public string Accarr10Endcode { get; set; }
        public short? Accarr10Acctype { get; set; }
        public short? Accarr10Remtype { get; set; }
        public short? Accarr10Tottype { get; set; }
        public string Accarr10Formula { get; set; }
        public double? Accarr10Total { get; set; }
        public int? Siteid { get; set; }
        public short? Recstatus { get; set; }
        public int? Orglogicref { get; set; }
        public string Orglogoid { get; set; }
        public short? Taxdecchck1 { get; set; }
        public short? Taxdecchck2 { get; set; }
        public short? Taxdecchck3 { get; set; }
        public short? Taxdecchck4 { get; set; }
        public string Countrycode { get; set; }
        public string Itemdefs { get; set; }
        public string Itemamounts { get; set; }
        public short? Taxassessmenttype { get; set; }
    }
}
