using System;
using System.Collections.Generic;

#nullable disable

namespace Layer.Core.Models
{
    public partial class LLdocnum
    {
        public int Logicalref { get; set; }
        public int? Dociden { get; set; }
        public int? Appmodule { get; set; }
        public int? Firmid { get; set; }
        public int? Divisid { get; set; }
        public int? Whid { get; set; }
        public int? Factid { get; set; }
        public int? Groupid { get; set; }
        public int? Roleid { get; set; }
        public int? Userid { get; set; }
        public string Firstnum { get; set; }
        public string Lastnum { get; set; }
        public DateTime? Effsdate { get; set; }
        public DateTime? Effedate { get; set; }
        public short? Numform { get; set; }
        public string Lastasgnd { get; set; }
        public string Owncode { get; set; }
        public string Segments1Segstart { get; set; }
        public string Segments1Segend { get; set; }
        public short? Segments1Seglen { get; set; }
        public short? Segments1Segattrb { get; set; }
        public short? Segments1Fillch { get; set; }
        public short? Segments1Segform { get; set; }
        public short? Segments1Increm { get; set; }
        public short? Segments1Txtlang { get; set; }
        public int? Segments1Resvd1 { get; set; }
        public int? Segments1Resvd2 { get; set; }
        public string Segments2Segstart { get; set; }
        public string Segments2Segend { get; set; }
        public short? Segments2Seglen { get; set; }
        public short? Segments2Segattrb { get; set; }
        public short? Segments2Fillch { get; set; }
        public short? Segments2Segform { get; set; }
        public short? Segments2Increm { get; set; }
        public short? Segments2Txtlang { get; set; }
        public int? Segments2Resvd1 { get; set; }
        public int? Segments2Resvd2 { get; set; }
        public string Segments3Segstart { get; set; }
        public string Segments3Segend { get; set; }
        public short? Segments3Seglen { get; set; }
        public short? Segments3Segattrb { get; set; }
        public short? Segments3Fillch { get; set; }
        public short? Segments3Segform { get; set; }
        public short? Segments3Increm { get; set; }
        public short? Segments3Txtlang { get; set; }
        public int? Segments3Resvd1 { get; set; }
        public int? Segments3Resvd2 { get; set; }
        public string Segments4Segstart { get; set; }
        public string Segments4Segend { get; set; }
        public short? Segments4Seglen { get; set; }
        public short? Segments4Segattrb { get; set; }
        public short? Segments4Fillch { get; set; }
        public short? Segments4Segform { get; set; }
        public short? Segments4Increm { get; set; }
        public short? Segments4Txtlang { get; set; }
        public int? Segments4Resvd1 { get; set; }
        public int? Segments4Resvd2 { get; set; }
        public string Segments5Segstart { get; set; }
        public string Segments5Segend { get; set; }
        public short? Segments5Seglen { get; set; }
        public short? Segments5Segattrb { get; set; }
        public short? Segments5Fillch { get; set; }
        public short? Segments5Segform { get; set; }
        public short? Segments5Increm { get; set; }
        public short? Segments5Txtlang { get; set; }
        public int? Segments5Resvd1 { get; set; }
        public int? Segments5Resvd2 { get; set; }
        public string Segments6Segstart { get; set; }
        public string Segments6Segend { get; set; }
        public short? Segments6Seglen { get; set; }
        public short? Segments6Segattrb { get; set; }
        public short? Segments6Fillch { get; set; }
        public short? Segments6Segform { get; set; }
        public short? Segments6Increm { get; set; }
        public short? Segments6Txtlang { get; set; }
        public int? Segments6Resvd1 { get; set; }
        public int? Segments6Resvd2 { get; set; }
        public string Segments7Segstart { get; set; }
        public string Segments7Segend { get; set; }
        public short? Segments7Seglen { get; set; }
        public short? Segments7Segattrb { get; set; }
        public short? Segments7Fillch { get; set; }
        public short? Segments7Segform { get; set; }
        public short? Segments7Increm { get; set; }
        public short? Segments7Txtlang { get; set; }
        public int? Segments7Resvd1 { get; set; }
        public int? Segments7Resvd2 { get; set; }
        public string Segments8Segstart { get; set; }
        public string Segments8Segend { get; set; }
        public short? Segments8Seglen { get; set; }
        public short? Segments8Segattrb { get; set; }
        public short? Segments8Fillch { get; set; }
        public short? Segments8Segform { get; set; }
        public short? Segments8Increm { get; set; }
        public short? Segments8Txtlang { get; set; }
        public int? Segments8Resvd1 { get; set; }
        public int? Segments8Resvd2 { get; set; }
        public string Segments9Segstart { get; set; }
        public string Segments9Segend { get; set; }
        public short? Segments9Seglen { get; set; }
        public short? Segments9Segattrb { get; set; }
        public short? Segments9Fillch { get; set; }
        public short? Segments9Segform { get; set; }
        public short? Segments9Increm { get; set; }
        public short? Segments9Txtlang { get; set; }
        public int? Segments9Resvd1 { get; set; }
        public int? Segments9Resvd2 { get; set; }
        public string Segments10Segstart { get; set; }
        public string Segments10Segend { get; set; }
        public short? Segments10Seglen { get; set; }
        public short? Segments10Segattrb { get; set; }
        public short? Segments10Fillch { get; set; }
        public short? Segments10Segform { get; set; }
        public short? Segments10Increm { get; set; }
        public short? Segments10Txtlang { get; set; }
        public int? Segments10Resvd1 { get; set; }
        public int? Segments10Resvd2 { get; set; }
        public string Segments11Segstart { get; set; }
        public string Segments11Segend { get; set; }
        public short? Segments11Seglen { get; set; }
        public short? Segments11Segattrb { get; set; }
        public short? Segments11Fillch { get; set; }
        public short? Segments11Segform { get; set; }
        public short? Segments11Increm { get; set; }
        public short? Segments11Txtlang { get; set; }
        public int? Segments11Resvd1 { get; set; }
        public int? Segments11Resvd2 { get; set; }
        public string Segments12Segstart { get; set; }
        public string Segments12Segend { get; set; }
        public short? Segments12Seglen { get; set; }
        public short? Segments12Segattrb { get; set; }
        public short? Segments12Fillch { get; set; }
        public short? Segments12Segform { get; set; }
        public short? Segments12Increm { get; set; }
        public short? Segments12Txtlang { get; set; }
        public int? Segments12Resvd1 { get; set; }
        public int? Segments12Resvd2 { get; set; }
        public string Segments13Segstart { get; set; }
        public string Segments13Segend { get; set; }
        public short? Segments13Seglen { get; set; }
        public short? Segments13Segattrb { get; set; }
        public short? Segments13Fillch { get; set; }
        public short? Segments13Segform { get; set; }
        public short? Segments13Increm { get; set; }
        public short? Segments13Txtlang { get; set; }
        public int? Segments13Resvd1 { get; set; }
        public int? Segments13Resvd2 { get; set; }
        public string Segments14Segstart { get; set; }
        public string Segments14Segend { get; set; }
        public short? Segments14Seglen { get; set; }
        public short? Segments14Segattrb { get; set; }
        public short? Segments14Fillch { get; set; }
        public short? Segments14Segform { get; set; }
        public short? Segments14Increm { get; set; }
        public short? Segments14Txtlang { get; set; }
        public int? Segments14Resvd1 { get; set; }
        public int? Segments14Resvd2 { get; set; }
        public string Segments15Segstart { get; set; }
        public string Segments15Segend { get; set; }
        public short? Segments15Seglen { get; set; }
        public short? Segments15Segattrb { get; set; }
        public short? Segments15Fillch { get; set; }
        public short? Segments15Segform { get; set; }
        public short? Segments15Increm { get; set; }
        public short? Segments15Txtlang { get; set; }
        public int? Segments15Resvd1 { get; set; }
        public int? Segments15Resvd2 { get; set; }
        public string Segments16Segstart { get; set; }
        public string Segments16Segend { get; set; }
        public short? Segments16Seglen { get; set; }
        public short? Segments16Segattrb { get; set; }
        public short? Segments16Fillch { get; set; }
        public short? Segments16Segform { get; set; }
        public short? Segments16Increm { get; set; }
        public short? Segments16Txtlang { get; set; }
        public int? Segments16Resvd1 { get; set; }
        public int? Segments16Resvd2 { get; set; }
        public int? Workid { get; set; }
        public int? Placeref { get; set; }
        public string Specode { get; set; }
        public string Placecode { get; set; }
        public short? Workarea { get; set; }
        public int? Termid { get; set; }
    }
}
