using System;
using System.Collections.Generic;

#nullable disable

namespace Layer.Core.Models
{
    public partial class Lv001SalesService
    {
        public int Period { get; set; }
        public short? SrvcardActive { get; set; }
        public string SrvcardActiveAdi { get; set; }
        public short? SrvcardCardtype { get; set; }
        public string SrvcardCode { get; set; }
        public string SrvcardDefinition { get; set; }
        public string SrvcardSpecode { get; set; }
        public string SrvcardCyphcode { get; set; }
        public string UnitsetfCode { get; set; }
        public string UnitsetfName { get; set; }
        public string UnitsetfSpecode { get; set; }
        public string UnitsetfCyphcode { get; set; }
        public string UnitsetlCode { get; set; }
        public string UnitsetlName { get; set; }
        public int? StlineLogicalref { get; set; }
        public short? StlineLinetype { get; set; }
        public string StlineSatirTuru { get; set; }
        public int? StlinePrevlineref { get; set; }
        public short? StlinePrevlineno { get; set; }
        public short? StlineTrcode { get; set; }
        public DateTime? StlineDate { get; set; }
        public int? StlineYear { get; set; }
        public int StlineHalf { get; set; }
        public int? StlineQuarter { get; set; }
        public int? StlineMonth { get; set; }
        public int? StlineWeek { get; set; }
        public int? StlineDay { get; set; }
        public int? StlineFtime { get; set; }
        public short? StlineGlobtrans { get; set; }
        public short? StlineSourceindex { get; set; }
        public short? StlineSourcecostgrp { get; set; }
        public short? StlineDestindex { get; set; }
        public short? StlineDestcostgrp { get; set; }
        public short? StlineIocode { get; set; }
        public string StlineIocodeTuru { get; set; }
        public int? StlineInvoiceref { get; set; }
        public short? StlineInvoicelnno { get; set; }
        public int? StlineClientref { get; set; }
        public int? StlineOrdtransref { get; set; }
        public int? StlineOrdficheref { get; set; }
        public string StlineSpecode { get; set; }
        public string StlineDelvrycode { get; set; }
        public double? StlineInputAmount { get; set; }
        public double? StlineOutputAmount { get; set; }
        public double? StlineInputPrice { get; set; }
        public double? StlineOutputPrice { get; set; }
        public double? StlineInputTotal { get; set; }
        public double? StlineOutputTotal { get; set; }
        public short? StlinePrcurr { get; set; }
        public double? StlineInputPrprice { get; set; }
        public double? StlineOutputPrprice { get; set; }
        public short? StlineTrcurr { get; set; }
        public double? StlineTrrate { get; set; }
        public double? StlineReportrate { get; set; }
        public double? StlineInputDistcost { get; set; }
        public double? StlineOutputDistcost { get; set; }
        public double? StlineInputDistdisc { get; set; }
        public double? StlineOutputDistdisc { get; set; }
        public double? StlineInputDistexp { get; set; }
        public double? StlineOutputDistexp { get; set; }
        public double? StlineInputDistprom { get; set; }
        public double? StlineOutputDistprom { get; set; }
        public double? StlineDiscper { get; set; }
        public string StlineLineexp { get; set; }
        public int? StlineUomref { get; set; }
        public int? StlineUsref { get; set; }
        public double? StlineUinfo1 { get; set; }
        public double? StlineUinfo2 { get; set; }
        public short? StlineVatinc { get; set; }
        public double? StlineVat { get; set; }
        public double? StlineInputVatamnt { get; set; }
        public double? StlineOutputVatamnt { get; set; }
        public double? StlineInputVatmatrah { get; set; }
        public double? StlineOutputVatmatrah { get; set; }
        public double? StlineInputOutcost { get; set; }
        public double? StlineOutputOutcost { get; set; }
        public short? StlineCancelled { get; set; }
        public double? StlineInputLinenet { get; set; }
        public double? StlineOutputLinenet { get; set; }
        public double? StlineInputDiffprcost { get; set; }
        public double? StlineOutputDiffprcost { get; set; }
        public double? StlineInputDiffrepprice { get; set; }
        public double? StlineOutputDiffrepprice { get; set; }
        public double? StlineInputDiffprcrcost { get; set; }
        public double? StlineOutputDiffprcrcost { get; set; }
        public short? InvoiceCancelled { get; set; }
        public string InvoiceCancelledAçiklama { get; set; }
        public short? InvoiceGrpcode { get; set; }
        public string InvoiceGrpcodeAçiklama { get; set; }
        public short? InvoiceTrcode { get; set; }
        public string InvoiceTrcodeAdi { get; set; }
        public string InvoiceFicheno { get; set; }
        public DateTime? InvoiceDate { get; set; }
        public int? InvoiceTime { get; set; }
        public string InvoiceDocode { get; set; }
        public string InvoiceSpecode { get; set; }
        public string InvoiceCyphcode { get; set; }
        public int? InvoiceClientref { get; set; }
        public int? InvoiceRecvref { get; set; }
        public double? InvoiceInputAdddiscounts { get; set; }
        public double? InvoiceOutputAdddiscounts { get; set; }
        public double? InvoiceInputTotaldiscounts { get; set; }
        public double? InvoiceOutputTotaldiscounts { get; set; }
        public double? InvoiceInputTotaldiscounted { get; set; }
        public double? InvoiceOutputTotaldiscounted { get; set; }
        public double? InvoiceInputAddexpenses { get; set; }
        public double? InvoiceOutputAddexpenses { get; set; }
        public double? InvoiceInputTotalexpenses { get; set; }
        public double? InvoiceOutputTotalexpenses { get; set; }
        public double? InvoiceInputTotaldepozito { get; set; }
        public double? InvoiceOutputTotaldepozito { get; set; }
        public double? InvoiceInputTotalpromotions { get; set; }
        public double? InvoiceOutputTotalpromotions { get; set; }
        public double? InvoiceInputTotalvat { get; set; }
        public double? InvoiceOutputTotalvat { get; set; }
        public double? InvoiceInputGrosstotal { get; set; }
        public double? InvoiceOutputGrosstotal { get; set; }
        public double? InvoiceInputNettotal { get; set; }
        public double? InvoiceOutputNettotal { get; set; }
        public double? InvoiceReportrate { get; set; }
        public double? InvoiceInputReportnet { get; set; }
        public double? InvoiceOutputReportnet { get; set; }
        public short? InvoiceTrcurr { get; set; }
        public double? InvoiceTrrate { get; set; }
        public double? InvoiceInputTrnet { get; set; }
        public double? InvoiceOutputTrnet { get; set; }
        public string ShipinfoCode { get; set; }
        public string ShipinfoName { get; set; }
        public string ShipinfoSpecode { get; set; }
        public string ShipinfoCyphcode { get; set; }
        public short? CapiwhouseNr { get; set; }
        public string CapiwhouseName { get; set; }
        public short? CapidivNr { get; set; }
        public string CapidivName { get; set; }
        public short? CapideptNr { get; set; }
        public string CapideptName { get; set; }
        public string ClcardCode { get; set; }
        public string ClcardDefinition { get; set; }
        public string ClcardSpecode { get; set; }
        public string ClcardTaxoffice { get; set; }
        public string ClcardTaxnr { get; set; }
        public string ClcardCyphcode { get; set; }
        public string ClcardIncharge { get; set; }
        public short? ClcardActive { get; set; }
        public string ClcardActiveAdi { get; set; }
        public string ClcardCity { get; set; }
        public string ClcardTradinggrp { get; set; }
        public short? ClcardCardtype { get; set; }
        public string ClcardCardtypeAdi { get; set; }
        public string PayplansCode { get; set; }
        public string PayplansDefinition { get; set; }
        public string PayplansSpecode { get; set; }
        public string PayplansCyphcode { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string EmcenterCode { get; set; }
        public string EmcenterDefinition { get; set; }
        public string SlsmanCode { get; set; }
        public string SlsmanDefinition { get; set; }
    }
}
