using System;
using System.Collections.Generic;

#nullable disable

namespace Layer.Core.Models
{
    public partial class Lv001OrderItem
    {
        public int Period { get; set; }
        public short? ClassActive { get; set; }
        public string ClassActiveAdi { get; set; }
        public short? ClassCardtype { get; set; }
        public string ClassCardtypeTipi { get; set; }
        public string ClassCode { get; set; }
        public string ClassName { get; set; }
        public string ClassStgrpcode { get; set; }
        public string ClassProducercode { get; set; }
        public string ClassSpecode { get; set; }
        public string ClassCyphcode { get; set; }
        public short? ItemsActive { get; set; }
        public string ItemsActiveAdi { get; set; }
        public short? ItemsCardtype { get; set; }
        public string ItemsMalzemeTipi { get; set; }
        public string ItemsCode { get; set; }
        public string ItemsName { get; set; }
        public string ItemsStgrpcode { get; set; }
        public string ItemsProducercode { get; set; }
        public string ItemsSpecode { get; set; }
        public string ItemsCyphcode { get; set; }
        public short? ItemsTracktype { get; set; }
        public string ItemsIzlemeTuru { get; set; }
        public string UnitsetfCode { get; set; }
        public string UnitsetfName { get; set; }
        public string UnitsetfSpecode { get; set; }
        public string UnitsetfCyphcode { get; set; }
        public string UnitsetlCode { get; set; }
        public string UnitsetlName { get; set; }
        public double? Itmunita2Katsayi { get; set; }
        public string Unitsetl2Code { get; set; }
        public string Unitsetl2Name { get; set; }
        public double? Itmunita3Katsayi { get; set; }
        public string Unitsetl3Code { get; set; }
        public string Unitsetl3Name { get; set; }
        public short? ItmunitaLinenr { get; set; }
        public string ItmunitaBarcode { get; set; }
        public double? ItmunitaWidth { get; set; }
        public string WidthCode { get; set; }
        public double? ItmunitaLength { get; set; }
        public string LengthCode { get; set; }
        public double? ItmunitaHeight { get; set; }
        public string HeightCode { get; set; }
        public double? ItmunitaArea { get; set; }
        public string AreaCode { get; set; }
        public double? ItmunitaVolume { get; set; }
        public string VolumeCode { get; set; }
        public double? ItmunitaGrossvolume { get; set; }
        public string GrossvolumeCode { get; set; }
        public double? ItmunitaWeight { get; set; }
        public string WeightCode { get; set; }
        public double? ItmunitaGrossweight { get; set; }
        public string GrossweightCode { get; set; }
        public double? ItmunitaConvfact1 { get; set; }
        public double? ItmunitaConvfact2 { get; set; }
        public int? OrflineLogicalref { get; set; }
        public short? OrflineLinetype { get; set; }
        public string OrflineSatirTuru { get; set; }
        public int? OrflinePrevlineref { get; set; }
        public short? OrflinePrevlineno { get; set; }
        public short? OrflineTrcode { get; set; }
        public DateTime? OrflineDate { get; set; }
        public int? OrflineYear { get; set; }
        public int OrflineHalf { get; set; }
        public int? OrflineQuarter { get; set; }
        public int? OrflineMonth { get; set; }
        public int? OrflineWeek { get; set; }
        public int? OrflineDay { get; set; }
        public int? OrflineTime { get; set; }
        public short? OrflineGlobtrans { get; set; }
        public short? OrflineSourceindex { get; set; }
        public short? OrflineSourcecostgrp { get; set; }
        public int? OrflineOrdficheref { get; set; }
        public short? OrflineLineno { get; set; }
        public int? OrflineClientref { get; set; }
        public string OrflineSpecode { get; set; }
        public string OrflineDelvrycode { get; set; }
        public double? OrflineInputAmount { get; set; }
        public double? OrflineOutputAmount { get; set; }
        public double? OrflineInputPrice { get; set; }
        public double? OrflineOutputPrice { get; set; }
        public double? OrflineInputTotal { get; set; }
        public double? OrflineOutputTotal { get; set; }
        public short? OrflinePrcurr { get; set; }
        public double? OrflineInputPrprice { get; set; }
        public double? OrflineOutputPrprice { get; set; }
        public short? OrflineTrcurr { get; set; }
        public double? OrflineTrrate { get; set; }
        public double? OrflineReportrate { get; set; }
        public double? OrflineInputDistcost { get; set; }
        public double? OrflineOutputDistcost { get; set; }
        public double? OrflineInputDistdisc { get; set; }
        public double? OrflineOutputDistdisc { get; set; }
        public double? OrflineInputDistexp { get; set; }
        public double? OrflineOutputDistexp { get; set; }
        public double? OrflineInputDistprom { get; set; }
        public double? OrflineOutputDistprom { get; set; }
        public double? OrflineDiscper { get; set; }
        public string OrflineLineexp { get; set; }
        public int? OrflineUomref { get; set; }
        public int? OrflineUsref { get; set; }
        public double? OrflineUinfo1 { get; set; }
        public double? OrflineUinfo2 { get; set; }
        public short? OrflineVatinc { get; set; }
        public double? OrflineVat { get; set; }
        public double? OrflineInputVatamnt { get; set; }
        public double? OrflineOutputVatamnt { get; set; }
        public double? OrflineInputVatmatrah { get; set; }
        public double? OrflineOutputVatmatrah { get; set; }
        public short? OrflineCancelled { get; set; }
        public double? OrflineInputLinenet { get; set; }
        public double? OrflineOutputLinenet { get; set; }
        public short? OrficheTrcode { get; set; }
        public string OrficheTrcodeAdi { get; set; }
        public string OrficheFicheno { get; set; }
        public DateTime? OrficheDate { get; set; }
        public int? OrficheTime { get; set; }
        public string OrficheDocode { get; set; }
        public string OrficheSpecode { get; set; }
        public string OrficheCyphcode { get; set; }
        public short? OrficheStatus { get; set; }
        public string OrficheStatusAdi { get; set; }
        public int? ForficheClientref { get; set; }
        public int? OrficheRecvref { get; set; }
        public double? OrficheInputAdddiscounts { get; set; }
        public double? OrficheOutputAdddiscounts { get; set; }
        public double? OrficheInputTotaldiscounts { get; set; }
        public double? OrficheOutputTotaldiscounts { get; set; }
        public double? OrficheInputTotaldiscounted { get; set; }
        public double? OrficheOutputTotaldiscounted { get; set; }
        public double? OrficheInputAddexpenses { get; set; }
        public double? OrficheOutputAddexpenses { get; set; }
        public double? OrficheInputTotalexpenses { get; set; }
        public double? OrficheOutputTotalexpenses { get; set; }
        public double? OrficheInputTotalpromotions { get; set; }
        public double? OrficheOutputTotalpromotions { get; set; }
        public double? OrficheInputTotalvat { get; set; }
        public double? OrficheOutputTotalvat { get; set; }
        public double? OrficheInputGrosstotal { get; set; }
        public double? OrficheOutputGrosstotal { get; set; }
        public double? OrficheInputNettotal { get; set; }
        public double? OrficheOutputNettotal { get; set; }
        public double? OrficheReportrate { get; set; }
        public double? OrficheInputReportnet { get; set; }
        public double? OrficheOutputReportnet { get; set; }
        public short? OrficheTrcurr { get; set; }
        public double? OrficheTrrate { get; set; }
        public double? OrficheInputTrnet { get; set; }
        public double? OrficheOutputTrnet { get; set; }
        public short? OrficheCancelled { get; set; }
        public string OrficheCancelledAçiklama { get; set; }
        public string ShipinfoCode { get; set; }
        public string ShipinfoName { get; set; }
        public string ShipinfoSpecode { get; set; }
        public string ShipinfoCyphcode { get; set; }
        public short? CapiwhouseNr { get; set; }
        public string CapiwhouseName { get; set; }
        public short? CapidivNr { get; set; }
        public string CapidivName { get; set; }
        public short? CapideptNr { get; set; }
        public string CapideptName { get; set; }
        public string ClcardCode { get; set; }
        public string ClcardDefinition { get; set; }
        public string ClcardSpecode { get; set; }
        public string ClcardTaxoffice { get; set; }
        public string ClcardTaxnr { get; set; }
        public string ClcardCyphcode { get; set; }
        public string ClcardIncharge { get; set; }
        public short? ClcardActive { get; set; }
        public string ClcardActiveAdi { get; set; }
        public string ClcardCity { get; set; }
        public string ClcardTradinggrp { get; set; }
        public short? ClcardCardtype { get; set; }
        public string ClcardCardtypeAdi { get; set; }
        public string PayplansCode { get; set; }
        public string PayplansDefinition { get; set; }
        public string PayplansSpecode { get; set; }
        public string PayplansCyphcode { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string EmcenterCode { get; set; }
        public string EmcenterDefinition { get; set; }
        public string SlsmanCode { get; set; }
        public string SlsmanDefinition { get; set; }
    }
}
